### DISCUSSION TITLE
Configuration via application.properties file

### DISCUSSION THREAD

**Discussion by PlugaruT** [Apicurio/apicurio-registry#1805] [Q&A] [answered]
Hi,
I am trying to use the `application.properties` file in order to configure some values for the registry. In `docker-compose.yml` file I am mounting a volume, something like this:
```
  apicurio:
    container_name: apicurio
    image: apicurio/apicurio-registry-sql:2.0.1.Final
    volumes:
      - ./cdc-conf/apicurio.properties:/home/jboss/config/application.properties
 ```
The content of the file is this:
```
registry.rules.global.compatibility=FULL
registry.rules.global.validity=BACKWARD_TRANSITIVE
registry.name=[LOCAL] Apicurio Registry
```
But, for some reason, the rules are not enabled at all.
What is the actual place to place the file for this? The [docs](https://quarkus.io/guides/config-reference#configuration-sources) says that the place is right.

**Comment by EricWittmann** [comment]
@jsenko or @famartinrh can you guys double-check how to do this?

**Reply by famarting** [reply]
I would suggest to use environment variables instead, i.e:
`REGISTRY_RULES_GOLBAL_COMPATIBILITY=FULL`

**Reply by PlugaruT** [reply]
Is this because it's not supported to use `application.properties`? I know about the env vars, but it would be easier for us to use the file.

**Reply by famarting** [reply]
we've never done that, I guess it should work

**Reply by PlugaruT** [reply]
I've tried with this docker compose config
```
  apicurio:
    container_name: apicurio
    image: apicurio/apicurio-registry-sql:2.0.1.Final
    volumes:
      - ./cdc-conf/apicurio.properties:/home/jboss/config/application.properties
    environment: 
      REGISTRY_DATASOURCE_URL: "jdbc:postgresql://apicurio-db/apicurio-registry"
      REGISTRY_DATASOURCE_USERNAME: "apicurio-registry"
      REGISTRY_DATASOURCE_PASSWORD: "password"
      REGISTRY_RULES_GLOBAL_COMPATIBILITY: "FULL"
      REGISTRY_RULES_GLOBAL_VALIDITY: "BACKWARD_TRANSITIVE"
    ports:
      - "8080"
    depends_on: 
      - apicurio-db
 ```
and does not seem to work for some reason.
Doing a `curl http://localhost:8081/apis/registry/v2/admin/rules` returns `[]` 🤔

**Reply by PlugaruT** [reply]
The only way I was able to enable the rules is via the env var like this `JAVA_OPTS: "-Dregistry.rules.global.compatibility=FULL"`
But I am not sure that this is the right way to do it as I am not really a Java expert and not familiar with the tooling.

**Reply by LittleWat** [reply]
You are setting the value oppositely:

If I set the following, they are set correctly
```env.yaml
env:
- name: REGISTRY_RULES_GLOBAL_COMPATIBILITY
  value: "BACKWARD"
- name: REGISTRY_RULES_GLOBAL_VALIDITY
  value: "FULL"
```

**Comment by PlugaruT** [comment, marked as answer]
Based on this answer, https://github.com/Apicurio/apicurio-registry/issues/733#issuecomment-914933091, mounting the file under `/deployments/config/application.properties` works as expected and Quarkus pick up the configuration.

**Comment by jonsnowseven** [comment]
Hello all.
So it is not possible to configure Apicurio Registry with env variables?

I am using this docker compose:

```yaml
services:
  apicurio:
    container_name: apicurio
    image: apicurio/apicurio-registry:3.0.6
    environment: 
      REGISTRY_RULES_GLOBAL_COMPATIBILITY: "BACKWARD"
      REGISTRY_REST_ARTIFACT_DELETION_ENABLED: "true"
    ports:
      - "8080"
    network_mode: host
```

But the env variables are not configuring the Registry as I desired.
