### DISCUSSION TITLE
Apicurio Registry Http Event Sink issue

### DISCUSSION THREAD

**Discussion by marcin-brzozowski** [Apicurio/apicurio-registry#2704] [Q&A]
Hi,

I'm trying to configure the ApicurioRegistry so that it sends CloudEvents to the configured HttpEventSink.
Apicurio Registry Version: `apicurio-registry-storage-sql:2.2.5.Final`
My docker-compose looks more or less like this:

```yaml
version: '3'

services:

  cloudevents-subscriber:
    image: 'cloudevents-subscriber:latest'
    container_name: cloudevents-subscriber
    environment:
      ASPNETCORE_URLS: 'http://+:5000'

  apicurio-registry-db:
    image: 'postgres:12.9'
    environment:
      POSTGRES_DB: ${APICURIO_REGISTRY_DATABASE}
      POSTGRES_USER: ${APICURIO_REGISTRY_DB_USER_NAME}
      POSTGRES_PASSWORD: ${APICURIO_REGISTRY_DB_PASSWORD}
    volumes:
      - 'postgre_apicurio_registry:/var/lib/postgresql/data'

  apicurio-registry:
    image: 'apicurio/apicurio-registry-sql:${APICURIO_REGISTRY_VERSION}'
    depends_on: [apicurio-registry-db]
    ports:
      - '8080:8080'
    environment:
      JAVA_TOOL_OPTIONS: '-Dregistry.events.sink.cloudevents-subscriber=http://cloudevents-subscriber:5000/api/events/receive'
      AUTH_ENABLED: ${APICURIO_REGISTRY_AUTH_ENABLED}
      KEYCLOAK_URL: ${APICURIO_REGISTRY_KEYCLOAK_URL}
      KEYCLOAK_REALM: ${APICURIO_REGISTRY_KEYCLOAK_REALM}
      KEYCLOAK_API_CLIENT_ID: ${APICURIO_REGISTRY_KEYCLOAK_API_CLIENT_ID}
      KEYCLOAK_UI_CLIENT_ID: ${APICURIO_REGISTRY_KEYCLOAK_UI_CLIENT_ID}
      REGISTRY_DATASOURCE_URL: ${APICURIO_REGISTRY_DB_CONNECTION_URL}
      REGISTRY_DATASOURCE_USERNAME: ${APICURIO_REGISTRY_DB_USER_NAME}
      REGISTRY_DATASOURCE_PASSWORD: ${APICURIO_REGISTRY_DB_PASSWORD}

volumes:
  postgre_apicurio_registry:

```

However, registry for some reason keeps trying to hit the `localhost/127.0.0.1:80` server:

```log
docker-compose-apicurio-registry-1          | 2022-08-18 17:42:01 INFO <> [io.apicurio.registry.events.http.HttpEventSink] (vert.x-eventloop-thread-1) Firing event io.apicurio.registry.artifact-updated
docker-compose-apicurio-registry-1          | 2022-08-18 17:42:01 ERROR <> [io.apicurio.registry.events.http.HttpEventSink] (vert.x-eventloop-thread-1) Error sending event to http://cloudevents-subscriber:5000/api/events/receive: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: localhost/127.0.0.1:80
docker-compose-apicurio-registry-1          | Caused by: java.net.ConnectException: Connection refused
```

There is one issue that I've managed to find, that looks like might be related: https://github.com/reactor/reactor-netty/issues/1405

I also tried logging inside the apicurio-registry container and manually sending a POST request to the `http://cloudevents-subscriber:5000/api/events/receive` endpoint using CURL and it worked perfectly fine. Is there something I mussed up with the configuration? Maybe setting the sink via `JAVA_TOOL_OPTIONS` somehow messed up the configuration? My knowledge of Java world is pretty limited. I would be grateful for any guidance. Thank you!
