### DISCUSSION TITLE
Authentication when verifying schemas?

### DISCUSSION THREAD

**Discussion by ivanpedersen** [Apicurio/apicurio-registry#3918] [General]
Hey, currently when I'm verifying schemas I'm using config like:

```
<groupId>io.apicurio</groupId>
<artifactId>apicurio-registry-maven-plugin</artifactId>
<version>${apicurio-registry-maven-plugin.version}</version>
<executions>
    <execution>
        <phase>generate-sources</phase>
        <goals>
            <goal>test-update</goal>
        </goals>
        <configuration>
            <registryUrl>${registry-url}</registryUrl>
            <authServerUrl>${auth-server-url}</authServerUrl> 
            <clientId>${client-id}</clientId>
            <clientSecret>${client-secret}</clientSecret>
...
```

But I would ideally want to be able to not specify my clientSecret, since it currently requires me to copy the secret around, even to local machines when compiling my project. I would want to not have to use any auth when verifying the schemas. Is it possible?

The documentation says:
> If authentication is required, you can specify your authentication server and client credentials.

https://www.apicur.io/registry/docs/apicurio-registry/2.4.x/getting-started/assembly-managing-registry-artifacts-maven.html#testing-artifacts-using-maven-plugin_registry

But it's not clear to me what this means? 

I've got services that don't specify any auth, and it's able to fetch schemas ok. In order to update any schemas though, I need auth ofc. Does this setup mean that I should be able to verify schemas as well without auth?
```
spring:
  kafka:
    properties:
      apicurio:
        registry:
          as-confluent: true
          headers:
            enabled: false
          use-specific-avro-reader: true
          artifact:
            group-id: "default"
          url: "https://apicurio.company.com/apis/registry/v2/"
```

I think we're using Keycloak in front of Apicurio if that makes any difference?
