### DISCUSSION TITLE
how to connect apicurio-registry to kafka connect ?

### DISCUSSION THREAD

**Discussion by RedEye-Developers** [Apicurio/apicurio-registry#6333] [Q&A]
how to connect apicurio-registry to kafka connect ?

**Comment by EricWittmann** [comment]
You can use one of our converters.  For example:

https://github.com/Apicurio/apicurio-registry/blob/main/utils/converter/src/main/java/io/apicurio/registry/utils/converter/AvroConverter.java

A full example using Debezium can be found here:

https://github.com/Apicurio/apicurio-registry/tree/main/examples/debezium-openshift

**Reply by RedEye-Developers** [reply]
```yaml
 debezium:
  image: debezium/connect:3.0.0.Final
  container_name: debezium
  hostname: debezium
  user: root
  depends_on:
   postgres:
    condition: service_healthy
   broker-1:
    condition: service_healthy
   broker-2:
    condition: service_healthy
   broker-3:
    condition: service_healthy
  ports:
   - '8083:8083'
  environment:
   BOOTSTRAP_SERVERS: 'broker-1:29091,broker-2:29092,broker-3:29093'
   CONNECT_REST_ADVERTISED_HOST_NAME: debezium
   GROUP_ID: 1
   CONFIG_STORAGE_TOPIC: connect_configs
   STATUS_STORAGE_TOPIC: connect_statuses
   OFFSET_STORAGE_TOPIC: connect_offsets
   KEY_CONVERTER: io.apicurio.registry.utils.converter.AvroConverter
   VALUE_CONVERTER: io.apicurio.registry.utils.converter.AvroConverter
   CONNECT_KEY_CONVERTER: io.apicurio.registry.utils.converter.AvroConverter
   CONNECT_VALUE_CONVERTER: io.apicurio.registry.utils.converter.AvroConverter
   CONNECT_KEY_CONVERTER_APICURIO_REGISTRY_URL: http://apicurio:8080 
   CONNECT_VALUE_CONVERTER_APICURIO_REGISTRY_URL: http://apicurio:8080
   CONNECT_KEY_CONVERTER_APICURIO_REGISTRY_AUTO-REGISTER: true
   CONNECT_VALUE_CONVERTER_APICURIO_REGISTRY_AUTO-REGISTER: true
   CONNECT_KEY_CONVERTER_APICURIO_REGISTRY_FIND-LATEST: true
   CONNECT_VALUE_CONVERTER_APICURIO_REGISTRY_FIND-LATEST: true
   CONNECT_SCHEMA_NAME_ADJUSTMENT_MODE: avro
   CONNECT_KEY_CONVERTER_SCHEMA_REGISTRY_URL: http://schema-registry:8081
   CONNECT_VALUE_CONVERTER_SCHEMA_REGISTRY_URL: http://schema-registry:8081
   ENABLE_DEBEZIUM_SCRIPTING: 'true'
   ENABLE_APICURIO_CONVERTERS: 'true'
  healthcheck:
   test:
     [ 'CMD', 'curl', '--silent', '--fail', '-X', 'GET', 'http://localhost:8083/connectors', ]
   start_period: 10s
   interval: 10s
   timeout: 5s
   retries: 5
  networks:
   mb-network:

 apicurio:
  image: apicurio/apicurio-registry:latest
  container_name: apicurio
  hostname: apicurio
  ports:
   - 8082:8080
  environment:
   APICURIO_STORAGE_KIND: 'sql'
   APICURIO_STORAGE_SQL_KIND: 'postgresql'
   APICURIO_DATASOURCE_URL: 'jdbc:postgresql://postgres:5432/postgres'
   APICURIO_DATASOURCE_USERNAME: postgres
   APICURIO_DATASOURCE_PASSWORD: postgres
  networks:
   mb-network:
  healthcheck:
   test: [ "CMD", "curl", "-f", "http://localhost:8080/health" ]
   interval: 10s
   timeout: 5s
   retries: 5
```

i mean i ask how to use apicurio.Avro converter same like this in debezium for kafka-connect ?

**Reply by RedEye-Developers** [reply]
```yaml
 kafka-connect:
  image: confluentinc/cp-kafka-connect:latest
  container_name: kafka-connect
  hostname: kafka-connect
  user: root
  ports:
   - "8084:8083"
  depends_on:
   - broker-1
   - broker-2
   - broker-3
  environment:
   CONNECT_BOOTSTRAP_SERVERS: 'broker-1:29091,broker-2:29092,broker-3:29093'
   CONNECT_REST_PORT: 8083 
   CONNECT_GROUP_ID: "kafka-connect" 
   CONNECT_CONFIG_STORAGE_TOPIC: "kafka-connect-config" 
   CONNECT_OFFSET_STORAGE_TOPIC: "kafka-connect-offsets" 
   CONNECT_STATUS_STORAGE_TOPIC: "kafka-connect-status" 
  # CONNECT_KEY_CONVERTER: "org.apache.kafka.connect.json.JsonConverter" 
  # CONNECT_VALUE_CONVERTER: "org.apache.kafka.connect.json.JsonConverter" 
   CONNECT_INTERNAL_KEY_CONVERTER: "org.apache.kafka.connect.json.JsonConverter" 
   CONNECT_INTERNAL_VALUE_CONVERTER: "org.apache.kafka.connect.json.JsonConverter" 
   CONNECT_REST_ADVERTISED_HOST_NAME: "localhost" 
   CONNECT_PLUGIN_PATH: /usr/share/java
   
   CONNECT_KEY_CONVERTER: io.apicurio.registry.utils.converter.AvroConverter
   CONNECT_VALUE_CONVERTER: io.apicurio.registry.utils.converter.AvroConverter
   CONNECT_KEY_CONVERTER_APICURIO_REGISTRY_URL: http://apicurio:8080
   CONNECT_VALUE_CONVERTER_APICURIO_REGISTRY_URL: http://apicurio:8080
   CONNECT_KEY_CONVERTER_APICURIO_REGISTRY_AUTO-REGISTER: true
   CONNECT_VALUE_CONVERTER_APICURIO_REGISTRY_AUTO-REGISTER: true
   CONNECT_KEY_CONVERTER_APICURIO_REGISTRY_FIND-LATEST: true
   CONNECT_VALUE_CONVERTER_APICURIO_REGISTRY_FIND-LATEST: true
   CONNECT_SCHEMA_NAME_ADJUSTMENT_MODE: avro
  networks:
   mb-network:
```

i try like this but it is throwing error like avro converter not found.
