### ISSUE TITLE
LOG_LEVEL change ingnored in v1.3.2

### ISSUE THREAD

**Issue by petolexa** [Apicurio/apicurio-registry#1230]
Hello,

if I change LOG_LEVEL in deployment of apicurio-streams image 1.3.2.Final to "DEBUG" like in example below, the log output level of k8s pod is not changed.

```
spec:
  containers:
    env:
      - name: LOG_LEVEL
         value: "DEBUG"
```

It works okay in latest-snapshot version, it works okay in red hat 1.0.0 version, but not in this 1.3.2.Final. Unfortunately in some environments I should only use latest Final version in my organization.

I tried the same with QUARKUS_LOG_LEVEL, or with adding JAVA_OPTS parameter -D%prod.quarkus.log.level=DEBUG, but nothing changed.

Is there any other option/workaround to raise log level in v1.3.2, or just wait until higher Final version is released?

Thank you,
Peter

**Comment by petolexa** [comment]
Hello,

if I change LOG_LEVEL in deployment of apicurio-streams image 1.3.2.Final to "DEBUG" like in example below, the log output level of k8s pod is not changed.
```
spec:
  containers:
    env:
      - name: LOG_LEVEL
         value: "DEBUG"
```

It works okay in latest-snapshot version, it works okay in red hat 1.0.0 version, but not in this 1.3.2.Final. Unfortunately in some environments I should only use latest Final version in my organization.

I tried the same with QUARKUS_LOG_LEVEL, or with adding JAVA_OPTS parameter -D%prod.quarkus.log.level=DEBUG, but nothing changed.

Is there any other option/workaround to raise log level in v1.3.2, or just wait until higher Final version is released?

Thank you,
Peter

**Comment by petolexa** [comment]
I am sorry for close and reopen, I fell into Enter key, while writing the description.

**Comment by famartinrh** [comment]
have you tried `-Dquarkus.log.level=DEBUG` ?

**Comment by EricWittmann** [comment]
How should that be configured in the yaml?

**Comment by petolexa** [comment]
Thank you for your answers. I tried this in yaml as JAVA_OPTIONS env part:
```
          env:
            - name: JAVA_OPTIONS
              value: "-D%prod.registry.streams.topology.storage.topic=test-schema-registry-storage-topic -D%prod.registry.streams.topology.global.id.topic=test-schema-registry-global-id-topic -D%prod.quarkus.log.level=DEBUG"

```

But I did't try -Dquarkus.log.level=DEBUG specifically, I will be able to try tomorrow soonest.

**Comment by petolexa** [comment]
> 
> 
> How should that be configured in the yaml?

And if you meant how I configured the env in yaml, I did it the same way as it is in [apicurio-registry-demo](https://github.com/Apicurio/apicurio-registry-demo/blob/4f4f6bb4ece9b6000b9890c74dab061c4c0705db/kubernetes/resources.yaml#L142)

I just changed env name from QUARKUS_LOG_LEVEL to LOG_LEVEL as this should be appropriate ENV from what I understand from application.properties file. Actually I tried both names to be sure.

**Comment by EricWittmann** [comment]
@famartinrh @jsenko If `-Dquarkus.log.level=DEBUG` doesn't work, any other ideas?  :(

**Comment by famartinrh** [comment]
looking at the properties for the [1.3.2.Final code](https://github.com/Apicurio/apicurio-registry/blob/1.3.x/app/src/main/resources/application.properties) one of these should work:

- `-Dquarkus.log.level=DEBUG`
- env var `QUARKUS_LOG_LEVEL`
- env var `LOG_LEVEL`

**Comment by petolexa** [comment]
Thank you for suggestions.
I tried this today:
```
          env:
            - name: JAVA_OPTIONS
              value: "-D%prod.registry.streams.topology.storage.topic=test-schema-registry-storage-topic -D%prod.registry.streams.topology.global.id.topic=test-schema-registry-global-id-topic -Dquarkus.log.level=DEBUG"
```

and it did not work.

I tried QUARKUS_LOG_LEVEL and LOG_LEVEL yesterday and it did not work as well.

Last thing I tried now was all these parameters together (complete deployment yaml):
```
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: apicurioregistry-test
  name: apicurioregistry-test
  namespace: schema-registry-test-01-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: apicurioregistry-test
  template:
    metadata:
      labels:
        app: apicurioregistry-test
    spec:
      containers:
        - image: nexus3.something.com:PORT/apicurio/apicurio-registry-streams:1.3.2.Final
          name: apicurioregistry-test
          ports:
            - containerPort: 8080
              protocol: TCP
          env:
            - name: JAVA_OPTIONS
              value: "-D%prod.registry.streams.topology.storage.topic=test-schema-registry-storage-topic -D%prod.registry.streams.topology.global.id.topic=test-schema-registry-global-id-topic -Dquarkus.log.level=DEBUG -D%prod.quarkus.log.level=DEBUG"
            - name: QUARKUS_PROFILE
              value: prod
            - name: KAFKA_BOOTSTRAP_SERVERS
              value: my-dev-kafka-cluster-kafka-bootstrap.local-kafka-dev-01-app:9092
            - name: APPLICATION_ID
              value: apicurioregistry-test
            - name: APPLICATION_SERVER_HOST
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: status.podIP
            - name: APPLICATION_SERVER_PORT
              value: "9000"
            - name: QUARKUS_LOG_LEVEL
              value: "DEBUG"
            - name: LOG_LEVEL
              value: "DEBUG"
          resources:
            limits:
              memory: "1000Mi"
          livenessProbe:
            httpGet:
              path: /health/live
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 5
            timeoutSeconds: 5
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /health/ready
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 5
            timeoutSeconds: 5
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
      imagePullSecrets:
        - name: nexus3
```
And unfortunatelly it did not work either. The output log of k8s pods is still in INFO level only.
