### ISSUE TITLE
Allow configuration of consumer group prefix

### ISSUE THREAD

**Issue by estahn** [Apicurio/apicurio-registry#1591]
I'm trying to set up ACLs for APICurio Registry and would like to limit the access of groups. I believe for this to work a "group prefix" will need to be added here:

https://github.com/Apicurio/apicurio-registry/blob/efe2dfc7f025323f8f0bccac74584f6fe0acb6c8/storage/kafkasql/src/main/java/io/apicurio/registry/storage/impl/kafkasql/KafkaSqlFactory.java#L176

**Current:**
```yaml
apiVersion: kafka.strimzi.io/v1beta1
kind: KafkaUser
metadata:
  name: {{ include "apicurio-registry.fullname" . }}
  labels:
    {{- include "apicurio-registry.labels" . | nindent 4 }}
    strimzi.io/cluster: {{ .Values.kafka.strimziCluster }}
spec:
  authentication:
    type: tls
  authorization:
    type: simple
    acls:
      - resource:
          type: topic
          name: {{ include "apicurio-registry.fullname" . }}-kafkasql-journal
          patternType: literal
        operation: All
      - operation: Read
        resource:
          name: '*'
          patternType: literal
          type: group
```

**Expected:**
```yaml
apiVersion: kafka.strimzi.io/v1beta1
kind: KafkaUser
metadata:
  name: {{ include "apicurio-registry.fullname" . }}
  labels:
    {{- include "apicurio-registry.labels" . | nindent 4 }}
    strimzi.io/cluster: {{ .Values.kafka.strimziCluster }}
spec:
  authentication:
    type: tls
  authorization:
    type: simple
    acls:
      - resource:
          type: topic
          name: {{ include "apicurio-registry.fullname" . }}-kafkasql-journal
          patternType: literal
        operation: All
      - operation: Read
        resource:
          name: '{{ include "apicurio-registry.fullname" . }}-'
          patternType: prefixed
          type: group
```
