### ISSUE TITLE
keycloak, roles, logout does not work with 2.1.0.Final but works with 2.0.0.Final

### ISSUE THREAD

**Issue by adamcodemaker** [Apicurio/apicurio-registry#1888]
I set up simple stack with keycloak and apicurio-registry 2.1.0.Final
I configured everything according to this
https://developers.redhat.com/articles/2021/07/16/how-secure-apache-kafka-schemas-red-hat-integration-service-registry-20#secure_your_registry_with_sso
I can sign in to apicurio-registry but
1. Roles dont work. Even readonly user can upload artifacts and change rules
![image](https://user-images.githubusercontent.com/25587877/135532899-6d49e27b-ee58-4adf-802e-a863653aaac8.png)
2. I can't logout using UI. Button does nothing
![image](https://user-images.githubusercontent.com/25587877/135532772-9fb196b9-666c-4898-bf11-a4262b2086f2.png)
I changed to apicurio-registry 2.0.0.Final end everything works as expected. 

```
version: '3'

volumes:
  postgres_data:
      driver: local

services:
  postgres:
      image: postgres
      volumes:
        - postgres_data:/var/lib/postgresql/data
      environment:
        POSTGRES_DB: keycloak
        POSTGRES_USER: keycloak
        POSTGRES_PASSWORD: password
  keycloak:
      image: quay.io/keycloak/keycloak:latest
      environment:
        DB_VENDOR: POSTGRES
        DB_ADDR: postgres
        DB_DATABASE: keycloak
        DB_USER: keycloak
        DB_SCHEMA: public
        DB_PASSWORD: password
        KEYCLOAK_USER: admin
        KEYCLOAK_PASSWORD: Pa55w0rd
        # Uncomment the line below if you want to specify JDBC parameters. The parameter below is just an example, and it shouldn't be used in production without knowledge. It is highly recommended that you read the PostgreSQL JDBC driver documentation in order to use it.
        #JDBC_PARAMS: "ssl=true"
      ports:
        - 8701:8080
      depends_on:
        - postgres
  apicurio:
    image: apicurio/apicurio-registry-mem:2.1.0.Final
    ports:
      - 8702:8080
    environment:
      AUTH_ENABLED: "true"
      KEYCLOAK_URL: http://192.168.0.90:8701/auth
      KEYCLOAK_REALM: registry
    depends_on:
      - keycloak
```
