### ISSUE TITLE
UI won't load after successful keycloak authentication

### ISSUE THREAD

**Issue by Bewi42** [Apicurio/apicurio-registry#1966]
Hello,

I have a problem where apicurio-registry UI won't load after successful keycloak authentication. I have the message "Loading, please wait..." displayed and nothing more happens

I have configured apicurio-registry to use keycloak for authent mechanism. Here is the compose file I use :
```
version: '3.4'

services:

  postgres-keycloak:
    image: postgres
    environment:
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: keycloak
      POSTGRES_DB: keycloak

  keycloak:
    image: jboss/keycloak
    ports:
      - 8090:8080
    environment:
      DB_VENDOR: postgres
      DB_ADDR: postgres-keycloak
      DB_USER: keycloak
      DB_PASSWORD: keycloak
      KEYCLOAK_IMPORT: /apicurio-keycloak-config/apicurio-realm.json
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
    volumes:
      - ./config/keycloak:/apicurio-keycloak-config
    depends_on:
      - postgres-keycloak

  postgres-apicurio:
    image: postgres
    environment:
      POSTGRES_USER: apicurio
      POSTGRES_PASSWORD: apicurio
      POSTGRES_DB: apicurio-registry

  apicurio:
    image: apicurio/apicurio-registry-sql:2.1.1.Final
    ports:
      - 8080:8080
    environment:
      REGISTRY_DATASOURCE_URL: 'jdbc:postgresql://postgres-apicurio/apicurio-registry'
      REGISTRY_DATASOURCE_USERNAME: apicurio
      REGISTRY_DATASOURCE_PASSWORD: apicurio
      AUTH_ENABLED: "true"
      # Beware : URL must be accessible by apicurio container and by client browser
      KEYCLOAK_URL: http://Ubuntu-VirtualBox:8090/auth
      KEYCLOAK_REALM: registry
      KEYCLOAK_API_CLIENT_ID: registry-api
      KEYCLOAK_UI_CLIENT_ID: apicurio-registry
    depends_on:
      - postgres-apicurio
      - keycloak
```

When compose has started, I log to keycloak admin UI with admin user. Then I add a "apicurio" user and I give the "sr-admin" role.

Then I log to apicurio-registry UI with this "apicurio" user and this is when I have the "Loading, please wait..." message.

I should add that when I disable authentication "AUTH_ENABLED: "false"", I am able to correctly display UI.
