### ISSUE TITLE
Environment variable to set topic name for event sourcing

### ISSUE THREAD

**Issue by Ferioney** [Apicurio/apicurio-registry#2630]
From documentation: Rregistry Cloud Events Registry](https://www.apicur.io/registry/docs/apicurio-registry/2.2.x/getting-started/assembly-configuring-the-registry.html#registry-cloud-events_registry):
```
You can configure cloud events in Apicurio Registry using Java system properties or equivalent environment variables.
```
 Now to provide the topic name for event sourcing I have to override `JAVA_OPTIONS` environment variable. My docker-compose file:
```
services:
  apicurio:
    ports:
      - 8080:8080
    environment:
      - JAVA_OPTIONS=-Dquarkus.http.host=0.0.0.0 -Djava.util.logging.manager=org.jboss.logmanager.LogManager **-Dregistry.events.kafka.topic=test_topic**
      - ets 
```

It would be nice to have an environment variable like `REGISTRY_EVENT_SOURCING_TOPIC` for property `registry.events.kafka.topic` (and the same for `registry.events.kafka.topic-partition` property)
