### ISSUE TITLE
When using apicurio with mongodb-kafka-connector, I get RESTEASY003210 error 

### ISSUE THREAD

**Issue by alizard0** [Apicurio/apicurio-registry#2889]
Hello,

I tried to set apicurio (v1.3.1) as the schema registry on my kafka-connect that is using mongodb-kafka-connector v1.7.0 to convert events to AVRO.

```yaml
value.converter: io.confluent.connect.avro.AvroConverter
value.converter.schema.registry.url: http://my-apicurio-service-registry/api
key.converter: io.confluent.connect.avro.AvroConverter
key.converter.schema.registry.url: http://my-apicurio-service-registry/api
```

When I apply the changes, the KafkaConnectors throws the following exception:

`Caused by: org.apache.kafka.common.config.ConfigException: Failed to access Avro data from topic my-topic-name : RESTEASY003210: Could not find resource for full path: http://my-apicurio-service-registry/api/subjects/my-topic-name/versions?normalize=false;  error code: 404`

I was checking the apicurio REST API and could not find any /api/subjects, therefore my question is, do apicurio supports this?
