### ISSUE TITLE
How should we configure to keep the schema after restarting the apicurio deployment?

### ISSUE THREAD

**Issue by LittleWat** [Apicurio/apicurio-registry#3145]
Hello! I am relatively new to Apicuiro. 

We set up the apicurio registry that uses kafka as its storage following the document.
- [Installing Apicurio Registry with Apache Kafka storage:: Apicurio Registry](https://www.apicur.io/registry/docs/apicurio-registry/2.4.x/getting-started/assembly-installing-registry-docker.html#installing-registry-kafka-storage_registry)

The deployment file is like as follows:

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: apicurio
  namespace: apicurio
  labels:
    app: apicurio
spec:
  replicas: 1
  selector:
    matchLabels:
      app: apicurio
  template:
    metadata:
      labels:
        app: apicurio
    spec:
      containers:
      - name: apicurio
        image: "apicurio/apicurio-registry-kafkasql:2.4.1.Final"
        imagePullPolicy: "IfNotPresent"
        ports:
        - name: schema-registry
          containerPort: 8080
          protocol: TCP
        resources:
          {}
        env:
        - name: KAFKA_BOOTSTRAP_SERVERS
          value: <MY_KAFKA_BOOTSTRAP_SERVERS>
        - name: REGISTRY_KAFKASQL_TOPIC
          value: "apicurio.data"
        - name: REGISTRY_KAFKASQL_CONSUMER_GROUP_ID
          value: "apicurio.registry"
        - name: REGISTRY_RULES_GLOBAL_VALIDITY
          value: "FULL"
```

The schema registration via the Apicurui UI works fine, however, after restarting the deployment (`$ kubectl rollout restart deployment -n apicurio apicurio`), the schema is lost.

I would like to keep the schema after restarting the deployment. Is it possible?
If possible, how should I configure?

Thank you!
