### ISSUE TITLE
Docker-compose integration with Keycloak. 

### ISSUE THREAD

**Issue by juliantxo163** [Apicurio/apicurio-registry#3277]
Hello.
I am facing the same issue that @ozarkblue have commented. 
I am doing a POC in docker with apicurio and keyloack, and I followed all the steps that I have found in differents docs. 
This is my apicurio and keyloack containers config:
 ```
  keycloak:
    image: quay.io/keycloak/keycloak:legacy
    #hostname: keycloak
    environment:
      DB_VENDOR: POSTGRES
      DB_ADDR: postgres
      DB_DATABASE: keycloak
      DB_USER: keycloak
      DB_SCHEMA: public
      DB_PASSWORD: password
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
      # Uncomment the line below if you want to specify JDBC parameters. The parameter below is just an example, and it shouldn't be used in production without knowledge. It is highly recommended that you read the PostgreSQL JDBC driver documentation in order to use it.
      #JDBC_PARAMS: "ssl=true"
    ports:
      - 9004:8080
    depends_on:
      - postgres
    networks:
      - trino-network
 apicurio:
    image: apicurio/apicurio-registry-kafkasql:2.4.2.Final
    #hostname: apicurio
    environment:
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      AUTH_ENABLED: true
      KEYCLOAK_URL: http://localhost:9004/auth
      KEYCLOAK_REALM: registry
      KEYCLOAK_API_CLIENT_ID: registry-api
      KEYCLOAK_UI_CLIENT_ID: apicurio-registry
      #REGISTRY_UI_CONFIG_APIURL: https://apicurio.julian.com/apis/registry
      #REGISTRY_UI_CONFIG_UIURL: https://apicurio.julian.com/ui  
    ports:
      - 9006:8080
    depends_on:
      - keycloak
      - kafka
    networks:
      - trino-network
```
Trino-network is a bridge network. 

I have configured the realms and clients in keyloack as this doc suggest: https://www.apicur.io/registry/docs/apicurio-registry/2.4.x/getting-started/assembly-configuring-the-registry.html#registry-security_registry

I have the same result that @ozarkblue have in the first comment, even I am not trying to secure it by SSL
<img width="677" alt="image" src="https://user-images.githubusercontent.com/35921456/231973202-fb282ccf-8335-4e7a-9694-8178685c4976.png">

<img width="671" alt="image" src="https://user-images.githubusercontent.com/35921456/231975451-b9a5945d-62cb-402c-a973-bc8a3430e8f5.png">

The same message if I try the URL http://localhost:9006/apis/registry/v2/users/me in other tab : {"username":"","displayName":"","admin":true,"developer":false,"viewer":false}

I also tried to set the vars  REGISTRY_UI_CONFIG_APIURL, REGISTRY_UI_CONFIG_UIURL  of but It doesnt work.. Have I need to configure any extra thing?

_Originally posted by @juliantxo163 in https://github.com/Apicurio/apicurio-registry/issues/2643#issuecomment-1508064113_
