### ISSUE TITLE
Anonymous read access via UI not working

### ISSUE THREAD

**Issue by mcharest-mcn** [Apicurio/apicurio-registry#3307]
## Description
In the UI at _{registry_url}/ui/settings_ in the **_Authorization settings_**

While trying to enable **_Anonymous read access_** through the UI interface, I get the following error : `ConfigPropertyNotFoundException: No configuration property named 'app.authn.anonymous-read-access.enabled' was found.`

Same thing with the _**Artifact owner-only authorization**_ :
`ConfigPropertyNotFoundException: No configuration property named 'app.authn.owner-only-authorization' was found.`

**Registry Version**: 2.4.2.Final
**Persistence type**: sql

### Environment
I was running some tests via a docker-compose with the following configuration :
```
version: '3.9'
services:
  apicurio:
    image: 686362239986.dkr.ecr.ca-central-1.amazonaws.com/base/apicurio/registry:2.4.2.Final
    container_name: apicurio
    depends_on:
      postgres_apicurio:
        condition: service_started
    environment:
      - REGISTRY_DATASOURCE_URL=jdbc:postgresql://postgres_apicurio:5432/apicurio-registry
      - REGISTRY_DATASOURCE_USERNAME=apicurio
      - REGISTRY_DATASOURCE_PASSWORD=motdepasse
      - KEYCLOAK_URL=https://{keycloak_url}/
      - KEYCLOAK_REALM=mcn-backend
      - KEYCLOAK_API_CLIENT_ID=apicurio_api
      - KEYCLOAK_UI_CLIENT_ID=apicurio_ui
      - REGISTRY_AUTH_ENABLED=true
      - REGISTRY_AUTH_RBAC_ENABLED=true
      - REGISTRY_AUTH_AUTHENTICATED_READS_ENABLED=true
      - REGISTRY_AUTH_ROLE_SOURCE=token
      - REGISTRY_AUTH_ROLES_ADMIN=sr-admin
    networks:
      - interne
    ports:
      - "80:8080"

  postgres_apicurio:
    image: {docker_registry_url}/base/postgres:14
    container_name: postgres_apicurio
    volumes:
      - apicuriodata:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=apicurio
      - POSTGRES_PASSWORD=motdepasse
      - POSTGRES_DB=apicurio-registry
    networks:
      - interne
    extra_hosts:
      - "host.docker.internal:127.0.0.1"

volumes:
  apicuriodata:
networks:
  interne:

```
Everything is running smoothly beside this minor bug.

### Steps to Reproduce
1. Run an instance of Apicurio Registry with OIDC authentication enabled
2. Access the settings through the UI
3. Try to enable **_Anonymous read access_** or _**Artifact owner-only authorization**_
4. Click on _Show details_ to see the error.

### Expected vs Actual Behaviour
We should be able to enable and disable **_Anonymous read access_** or _**Artifact owner-only authorization**_ without any error.

### Logs
```
apicurio           | 2023-05-01 17:03:52 INFO <_> [io.apicurio.common.apps.logging.audit.AuditLogService] (executor-thread-111) apicurio.audit action="request" result="failure" src_ip="{source_ip}" path="/apis/registry/v2/admin/config/properties/registry.auth.anonymous-read-access.enabled" response_code="404" method="PUT" user=""
```
