### ISSUE TITLE
Use of .well-known config to access Keycloak endpoints

### ISSUE THREAD

**Issue by mcharest-mcn** [Apicurio/apicurio-registry#3308]
### Feature or Problem Description
While trying to configure OIDC through Keycloak, I identified the following environment variables to specify the Keycloak URL :

- KEYCLOAK_URL
- TOKEN_ENDPOINT
- REGISTRY_AUTH_URL_CONFIGURED

The problem is that while using http://keycloak:8080 to access Keycloak from the backend side, I need to configure http://127.0.0.1:8080 as the keycloak URL to be able to access the authentication endpoint from the browser.

I can configured the different endpoints in Keycloak's .well-known config, but the URLs used by Apicurio don't seem to be using it to reference the different endpoints.

### Proposed Solution
Use the Keycloak .well-known config to configure all the endpoints used by Apicurio Registry.
_https://{keycloak_url}/realms/{realm}/.well-known/openid-configuration_

By doing so, we would give more control to the users over their Keycloak installation.

### Additional Context

```
version: '3.9'
services:

  keycloak:
    image: quay.io/keycloak/keycloak:21.1.1
    container_name: keycloak
    depends_on:
      postgres:
        condition: service_started
    ports:
      - "8080:8080"
      - "8443:8443"
    networks:
      - interne
    command: ["start-dev"]
    healthcheck:
      test: ["CMD", "curl", "--head", "-fsS", "http://localhost:8080/health/ready"]
      interval: 11s
      timeout: 10s
      retries: 3
      start_period: 40s
    environment:
      - KC_SPI_WELL_KNOWN_OPENID_CONFIGURATION_OPENID_CONFIGURATION_OVERRIDE=/opt/keycloak/openid-configuration-override.json
      - KC_HEALTH_ENABLED=true
      - KC_DB=postgres
      - KC_HOSTNAME_STRICT=false
      - KC_DB_URL=jdbc:postgresql://postgres/keycloak
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
      - KC_DB_USERNAME=keycloak
      - KC_DB_PASSWORD=motdepasse
      - KC_MESSAGE_TOGGLE=false

  postgres:
    image: postgres:14
    container_name: postgres
    volumes:
      - keycloakdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=keycloak
      - POSTGRES_PASSWORD=motdepasse
      - POSTGRES_DB=keycloak
    networks:
      - interne
    ports:
      - "5432:5432"
    extra_hosts:
      - "host.docker.internal:127.0.0.1"

  apicurio:
    image: apicurio/apicurio-registry-sql:2.4.2.Final
    container_name: apicurio
    depends_on:
      postgres_apicurio:
        condition: service_started
      keycloak:
        condition: service_healthy
    environment:
      - REGISTRY_DATASOURCE_URL=jdbc:postgresql://postgres_apicurio:5432/apicurio-registry
      - REGISTRY_DATASOURCE_USERNAME=apicurio
      - REGISTRY_DATASOURCE_PASSWORD=motdepasse
      - KEYCLOAK_URL=https://127.0.0.1:8080/
#      - TOKEN_ENDPOINT=http://keycloak:8080/realms/registry/protocol/openid-connect/token
      - KEYCLOAK_REALM=mcn-backend
      - KEYCLOAK_API_CLIENT_ID=apicurio_api
      - KEYCLOAK_UI_CLIENT_ID=apicurio_ui
      - REGISTRY_AUTH_URL_CONFIGURED=http://keycloak:8080/realms/registry/
      - REGISTRY_AUTH_ENABLED=true
      - REGISTRY_AUTH_RBAC_ENABLED=true
      - REGISTRY_AUTH_AUTHENTICATED_READS_ENABLED=true
      - REGISTRY_AUTH_ROLE_SOURCE=token
      - REGISTRY_AUTH_ROLES_ADMIN=sr-admin
    networks:
      - interne
    ports:
      - "80:8080"

  postgres_apicurio:
    image: postgres:14
    container_name: postgres_apicurio
    volumes:
      - apicuriodata:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=apicurio
      - POSTGRES_PASSWORD=motdepasse
      - POSTGRES_DB=apicurio-registry
    networks:
      - interne
    extra_hosts:
      - "host.docker.internal:127.0.0.1"

volumes:
  keycloakdata:
  apicuriodata:
networks:
  interne:
```
