### ISSUE TITLE
Documentation tab for AsyncAPI following specification > 2.4 gives Error: Version X not supported

### ISSUE THREAD

**Issue by forsberg** [Apicurio/apicurio-registry#3350]
## Description

**Registry Version**:  2.4.2.Final
**Persistence type**: sql

### Steps to Reproduce

1. Upload an AsyncAPI API specification marked as asyncapi version 2.5.0 or 2.6.0. I used the [hello world example from asyncapi.com](https://www.asyncapi.com/docs/tutorials/getting-started/hello-world), i.e this:

```yaml
asyncapi: 2.6.0
info:
  title: Hello world application
  version: '0.1.0'
channels:
  hello:
    publish:
      message:
        payload:
          type: string
          pattern: '^hello .+$'
```

2. Try to inspect Documentation of newly uploaded API

### Expected vs Actual Behaviour

Expected nicely formatted documentation with channels, messages etc.

Instead got an error message: `Error: Version 2.6.0 is not supported.`

Same thing if I change asyncapi version to 2.5.0
