### ISSUE TITLE
AVRO with different field order are considered equal in canonical form

### ISSUE THREAD

**Issue by swehner** [Apicurio/apicurio-registry#4215]
## Description

** NOTE: I've just seen that the commit from the main branch that makes this the default behavior isn't in the latest release. When do you plan to release this commit? https://github.com/Apicurio/apicurio-registry/commit/4971edeccdad8aa31d9133c87a1f226afae0888f **

**Registry
Version**: 2.5.8.Final
**Persistence type**: "in-memory"

I'm trying to figure out what the schema equivalency is when changing whitespace, property order, etc.
We're having an issue where debezium source is reordering the fields inside a record after some idempotent modifications. We are using the canonical hash and apicurio seems to think two schemas with different field order in a record are the same.
I've tried to reproduce it both with the apicurio native api and the ccompat api and both show the same behavior when canonical normalization is turned on.

I thought that after #300 changes in field order should make two schemas non-equivalent.
Can you confirm whether there is a bug, or whether I'm using it the wrong way?

### Environment

Running locally with doker-compose:
```
version: '2'
services:
  #############################################################
  # Apicurio Registry                                         #
  #############################################################
  apicurioregistry:
    image: apicurio/apicurio-registry-mem:2.5.8.Final
    hostname: apicurio
    container_name: apicurio
    ports:
      - "28080:8080"
    environment:
      - ENABLE_CCOMPAT_CANONICAL_HASH_MODE=false
      - LOG_LEVEL=DEBUG
```

### Steps to Reproduce

```
#!/bin/bash

c () {
  curl -d @/dev/stdin -X POST -H "Content-Type: application/json; artifactType=AVRO" \
  -H "X-Registry-ArtifactId: lastseen" \
  'http://localhost:28080/apis/registry/v2/groups/group/artifacts?canonical=true'
}

u () {
  curl -d @/dev/stdin -X POST -H "Content-Type: application/json; artifactType=AVRO" \
  'http://localhost:28080/apis/registry/v2/groups/group/artifacts/lastseen/meta?canonical=true'
}

echo Expect creation
cat schema_start.json | c

echo -e "\nExpect it to be found"
cat schema_start.json | u

echo -e "\nChange whitespace - expect it to be found"
cat schema_ws_change.json | u

echo -e "\nReorder fields - shouldn't find"
cat reordered_fields.json | u
```

schema_start.json:
```
{
  "type": "record",
  "name": "lastseen",
  "fields": [
    {
      "name": "app_config_id",
      "type": [
        "long",
        "null"
      ]
    },
    {
      "name": "app_user_id",
      "type": [
        "string",
        "null"
      ]
    }
  ]
}
```

schema_ws_change.json:
```
{
"type": "record",
"name": "lastseen",
"fields": [
{
"name": "app_config_id",
"type": [
"long",
"null"
]
},
{
"name": "app_user_id",
"type": [
"string",
"null"
]
}
]
}
```

reordered_fields.json:
```
{
  "type": "record",
  "name": "lastseen",
  "fields": [
    {
      "name": "app_user_id",
      "type": [
        "string",
        "null"
      ]
    },
    {
      "name": "app_config_id",
      "type": [
        "long",
        "null"
      ]
    }
  ]
}
```

### Expected vs Actual Behaviour

Expected: For `reordered_fields.json` no schema is found

Actual:
The schema is retrieved even with a different field order.
```
Expect creation
{"name":"lastseen","createdBy":"","createdOn":"2024-01-16T16:47:06+0000","modifiedBy":"","modifiedOn":"2024-01-16T16:47:06+0000","id":"lastseen","version":"1","type":"AVRO","globalId":1,"state":"ENABLED","groupId":"group","contentId":1,"references":[]}
]
Change whitespace - expect it to be found
{"version":"1","name":"lastseen","createdBy":"","createdOn":"2024-01-16T16:47:06+0000","type":"AVRO","globalId":1,"state":"ENABLED","id":"lastseen","groupId":"group","contentId":1}

Reorder fields - shouldn't find
{"version":"1","name":"lastseen","createdBy":"","createdOn":"2024-01-16T16:47:06+0000","type":"AVRO","globalId":1,"state":"ENABLED","id":"lastseen","groupId":"group","contentId":1}
```

The same happens when using `ccompat/v7` api with `normalize=true` or when enabling the env var `ENABLE_CCOMPAT_CANONICAL_HASH_MODE`

### Logs

No relevant logs in registry
