### ISSUE TITLE
Question about postgres storage

### ISSUE THREAD

**Issue by pyjos** [Apicurio/apicurio-registry#4681]
Hello!

This is probably more of a user issue than anything - but I was looking to get apicurio setup using the postgres storage option

While I can get the service up and running using the instructions located [here](https://github.com/Apicurio/apicurio-registry?tab=readme-ov-file#docker-containers)

For some reason - the data isn't persisted in postgres

When I bring use the following `docker-compose.yaml` - I don't see any tables under psql?
```
version: "3.1"

services:
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: apicurio-registry
      POSTGRES_PASSWORD: password
      PG_DATA: postgres
    volumes:
      - postgres:/data/postgres
  app:
    image: apicurio/apicurio-registry:latest-snapshot
    ports:
      - 8080:8080
    environment:
      APICURIO_STORAGE_KIND: "sql"
      APICURIO_STORAGE_DB_KIND: "postgresql"
      REGISTRY_DATASOURCE_URL: "jdbc:postgresql://postgres/apicurio-registry"
      REGISTRY_DATASOURCE_USERNAME: apicurio-registry
      REGISTRY_DATASOURCE_PASSWORD: password
    depends_on:
      - postgres

volumes:
  postgres:
```
```
docker exec -it <container-id> /bin/bash
psql -U apicurio-registry -h localhost -p 5432
```

![image](https://github.com/Apicurio/apicurio-registry/assets/170106801/41cb7c23-d0c8-4060-907e-0341444d257d)

However - if I bring it up with the `sql` image - I do see the tables

![image](https://github.com/Apicurio/apicurio-registry/assets/170106801/ab2332d7-6847-4c1f-b146-b0469d7b1616)

But I don't see the data being persisting between container shut down / start up (not removing the volume) - was there something that I missed?
