### ISSUE TITLE
Error loading role mappings.

### ISSUE THREAD

**Issue by abhipatil2001** [Apicurio/apicurio-registry#6045]
## Description
I am unable to access the 'Access' section in Apicurio Registry v3.0.6 (latest-release) using the URL:
http://localhost:8888/roles

This request hits the following endpoint:
`http://localhost:8080/apis/registry/v3/admin/roleMappings?limit=100&offset=0`

However, it returns a 403 Forbidden error, even when logged in as an admin user.

**Registry
Version**:  3.0.6 (I have taken latest-release in docker compose) 

### Environment
Docker compose

### Steps to Reproduce

1. Deploy Apicurio Registry using the provided Docker Compose file.
2. Enable authentication and authorization using Keycloak.
3. Log in as an admin user.
4. Navigate to 'Access' (http://localhost:8888/roles).
5. Observe the 403 Forbidden error.

For more details here is attached screenshot:

![Image](https://github.com/user-attachments/assets/9136d795-454a-4d14-b3cf-1762129932ec)

and following are the logs of registry: 

```
apicurio-registry   | 2025-03+00-18 01:04:10 WARN [io.apicurio.registry.auth.AuthorizedInterceptor] (executor-thread-4) Access to /admin/roleMappings denied because application managed RBAC is not enabled.
apicurio-registry   | 2025-03+00-18 01:04:10 INFO [io.apicurio.registry.logging.audit.AuditLogService] (executor-thread-4) apicurio.audit action="request" result="failure" src_ip="172.20.0.1" path="/apis/registry/v3/admin/roleMappings" response_code="403" method="GET" user="" 
apicurio-registry   | 2025-03+00-18 01:04:10 INFO [io.quarkus.vertx.http.runtime.filters.accesslog.JBossLoggingAccessLogReceiver] (executor-thread-4) "apicurio-registry.access method="GET" path="/apis/registry/v3/admin/roleMappings?limit=100&offset=0" response_code="403" response_time="-" remote_ip="172.20.0.1" remote_user="-" user_agent="Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/133.0.0.0 Safari/537.36""
apicurio-registry   | 2025-03+00-18 01:04:10 INFO [io.apicurio.registry.auth.AuthorizedInterceptor] (executor-thread-23) principalId:admin
apicurio-registry   | 2025-03+00-18 01:04:10 INFO [io.apicurio.registry.auth.AuthorizedInterceptor] (executor-thread-23) roles:[offline_access, default-roles-registry, uma_authorization, sr-admin]
```

this errors I am getting even if I have enabled RBAC and can ensure Successfull authentication and authorization.

 authentication and authorization has enabled from docker compose  environment variables of apicurio.
keycloak is used for AUTH and RBAC provider
 My compose file:
(this is my localhost setup)
```
backend:
    image: quay.io/apicurio/apicurio-registry:latest-release
    container_name: apicurio-registry
    restart: unless-stopped
    ports: 
      - "8080:8080"
    environment:
      apicurio.rest.deletion.group.enabled: "true"
      apicurio.rest.deletion.artifact.enabled: "true"
      apicurio.rest.deletion.artifact-version.enabled: "true"
      apicurio.rest.mutability.artifact-version-content.enabled: "true"
      apicurio.auth.role-based-authorization: "true"
      QUARKUS_HTTP_PORT: "8080"             
      QUARKUS_PROFILE: "prod"
      APICURIO_STORAGE_KIND: "sql"
      APICURIO_STORAGE_SQL_KIND: "PostgreSQL"
      APICURIO_DATASOURCE_URL: "jdbc:postgresql://192.168.2.199:5433/apicurio-registry"
      APICURIO_DATASOURCE_USERNAME: "root"
      APICURIO_DATASOURCE_PASSWORD: "root"
      QUARKUS_OIDC_TENANT_ENABLED: "true"
      QUARKUS_OIDC_AUTH_SERVER_URL: "http://192.168.2.199:22001/realms/registry"
      QUARKUS_OIDC_AUTH_SERVER_URL: "http://192.168.1.107:22001/realms/registry"
      QUARKUS_OIDC_CLIENT_ID: "registry-api"
      APICURIO_UI_AUTH_OIDC_CLIENT-ID: "apicurio-registry"
      APICURIO_UI_AUTH_OIDC_REDIRECT-URI: "http://localhost:8888/"
      APICURIO_AUTH_ROLE_BASED_AUTHORIZATION: "true"
      APICURIO_AUTH_AUTHENTICATED_READ_ACCESS_ENABLED: "true"
      QUARKUS_OIDC_TLS_VERIFICATION: "none"
      QUARKUS_HTTP_CORS_ORIGINS: "*"
  
  ui:
    image: quay.io/apicurio/apicurio-registry-ui:latest-release
    environment:
      REGISTRY_API_URL: "http://localhost:8080/apis/registry/v3"
      REGISTRY_AUTH_TYPE: "oidc"
      REGISTRY_AUTH_RBAC_ENABLED: "true"
      REGISTRY_AUTH_URL: "http://192.168.2.199:22001/realms/registry"
      REGISTRY_AUTH_CLIENT_ID: "apicurio-registry"
      REGISTRY_AUTH_REDIRECT_URL: "http://localhost:8888/"
      REGISTRY_AUTH_LOGOUT_URL: "http://localhost:8888/explore"
      REGISTRY_FEATURE_READ_ONLY: "true"
      REGISTRY_FEATURE_BREADCRUMBS: "true"
      REGISTRY_DELETE_GROUP_ENABLED: "true"
      REGISTRY_DELETE_ARTIFACT_ENABLED: "true"
      REGISTRY_DELETE_VERSION_ENABLED: "true"
    ports:
      - "8888:8080"
    depends_on:
      - backend

  apicurio-studio-ui:
    image: quay.io/apicurio/apicurio-studio-ui:1.1.0-Beta3
    container_name: apicurio-ui
    restart: unless-stopped
    ports:
      - "8082:8080"
    environment:
      JAVA_TOOL_OPTIONS: "-Djava.net.preferIPv4Stack=true"
      QUARKUS_HTTP_PORT: "8082"
      QUARKUS_PROFILE: "prod"

      APICURIO_REGISTRY_API_URL: "http://localhost:8080/apis/registry/v3"
      APICURIO_REGISTRY_UI_URL: "http://localhost:8888"
      APICURIO_SHOW_MASTHEAD: "true"
      APICURIO_MASTHEAD_LABEL: "Apicurio Studio"
      APICURIO_UI_FEATURE_MICROCKS: true

      APICURIO_AUTH_TYPE: "oidc"
      APICURIO_AUTH_URL: "http://192.168.1.107:22001/realms/registry"
      REGISTRY_AUTH_RBAC_ENABLED: "true"
      APICURIO_AUTH_CLIENT_ID: "apicurio-studio"
      APICURIO_AUTH_REDIRECT_URL: "http://localhost:8082/"
      REGISTRY_FEATURE_BREADCRUMBS: "true"
      FEATURE_ROLE_MANAGEMENT: "true"
      FEATURE_SETTINGS: "true"

      APICURIO_OIDC_REDIRECT_HTTPS: "false"
    depends_on:
      - backend
``` 

> here you may see redundant variables but those are added for testing purpose

Let me grab my Keycloak setting quickly, 

![Image](https://github.com/user-attachments/assets/19f4ba5c-4b8d-4409-a678-44f6b29941b1)

![Image](https://github.com/user-attachments/assets/17fa7880-56b2-4605-b5ea-3d28ff142bed)

![Image](https://github.com/user-attachments/assets/74d5c10f-c144-4dc1-a8d3-20be1084d161)
I was able to authorize using realm roles that applicable to all clients. but for this specifc endpoint I also modified client specific client scope. In which I have given User Realme Role as mapper and "resource_access.apicurio-registry.roles"  as token claim so that sr-admin can access the resources of registry as well.
**But this is also not working.**

![Image](https://github.com/user-attachments/assets/0ac1ecbd-c6f2-4073-b03a-d10f295151b2)
This are my realm roles that are applicable to all clients.

**This is the current token breakdown:**

```
{
  "exp": 1742262386,
  "iat": 1742262086,
  "jti": "2fd02291-88e9-4144-9781-edeb5d043535",
  "iss": "http://localhost:22001/realms/registry",
  "aud": "account",
  "sub": "495c28d2-e0a0-4083-be0c-ee59c5481ba6",
  "typ": "Bearer",
  "azp": "apicurio-registry",
  "session_state": "889754e3-a673-417d-a507-3ac1cc35c700",
  "acr": "1",
  "allowed-origins": [
    "*"
  ],
  "realm_access": {
    "roles": [
      "offline_access",
      "default-roles-registry",
      "uma_authorization",
      "sr-admin"
    ]
  },
  "resource_access": {
    "apicurio-registry": {
      "roles": [
        "offline_access",
        "default-roles-registry",
        "uma_authorization",
        "sr-admin"
      ]
    },
    "account": {
      "roles": [
        "manage-account",
        "manage-account-links",
        "view-profile"
      ]
    }
  },
  "scope": "email profile",
  "sid": "889754e3-a673-417d-a507-3ac1cc35c700",
  "email_verified": false,
  "preferred_username": "admin",
  "given_name": "",
  "family_name": ""
}

```
### Expected vs Actual Behaviour
I can access other endpoints like `http://localhost:8080/apis/registry/v3/admin/rules`

![Image](https://github.com/user-attachments/assets/920d8e03-fe72-49ff-afc8-f9c1410bcec3)

But unable to access rolemapping even if I have enabled authentication and authorization.

### Logs

apicurio-registry container:

```
apicurio-registry   | 2025-03+00-18 02:00:56 WARN [io.apicurio.registry.auth.AuthorizedInterceptor] (executor-thread-1) Access to /admin/roleMappings denied because application managed RBAC is not enabled.
apicurio-registry   | 2025-03+00-18 02:00:56 INFO [io.apicurio.registry.logging.audit.AuditLogService] (executor-thread-1) apicurio.audit action="request" result="failure" src_ip="172.20.0.1" path="/apis/registry/v3/admin/roleMappings" response_code="403" method="GET" user="" 
apicurio-registry   | 2025-03+00-18 02:00:56 INFO [io.quarkus.vertx.http.runtime.filters.accesslog.JBossLoggingAccessLogReceiver] (executor-thread-1) "apicurio-registry.access method="GET" path="/apis/registry/v3/admin/roleMappings?limit=100&offset=0" response_code="403" response_time="-" remote_ip="172.20.0.1" remote_user="-" user_agent="Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36""
apicurio-registry   | 2025-03+00-18 02:00:56 INFO [io.apicurio.registry.auth.AuthorizedInterceptor] (executor-thread-4) principalId:admin
apicurio-registry   | 2025-03+00-18 02:00:56 INFO [io.apicurio.registry.auth.AuthorizedInterceptor] (executor-thread-4) roles:[offline_access, default-roles-registry, uma_authorization, sr-admin]
apicurio-registry   | 2025-03+00-18 02:00:56 INFO [io.quarkus.vertx.http.runtime.filters.accesslog.JBossLoggingAccessLogReceiver] (executor-thread-4) "apicurio-registry.access method="GET" path="/apis/registry/v3/users/me" response_code="200" response_time="-" remote_ip="172.20.0.1" remote_user="admin" user_agent="Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36""
```

![Image](https://github.com/user-attachments/assets/dcfe9ad9-d038-4634-bce7-e3c513341acc)

apicurio-registry-ui container: 

![Image](https://github.com/user-attachments/assets/1691d610-eb66-4bc3-9e06-52d7dd6739d9)

**"Please look into this and help resolve the issue. Any additional support or suggestions would be greatly appreciated."**

**Comment by abhipatil2001** [comment]
@EricWittmann & @carlesarnal would you please help me on this above issue. The authorization is not working properly for that particular endpoint.

**Comment by EricWittmann** [comment]
Hi @abhipatil2001 - the problem here is that you have RBAC enabled but the **role source** is not set to `application`.  I'll explain. :)

## Explanation

Registry supports different sources for the roles.  By default, it will look in the JWT for the user's roles.  That's the most common way to use RBAC.  In that case, we defer to Keycloak for assigning roles to users.  The application will look into the JWT for the roles assigned to the user.  It will then make authorization decisions based on those roles.

However, it's also **possible** to use the application's database as the role source instead of the JWT.  To do that, you can set the `apicurio.auth.role-source` property to `application`.  When you do that, Registry will maintain a table in its own database for the roles assigned to different users.  This is not the typical configuration, but it is possible.

**Note**:  when you use application managed roles, you will still need a way to identify the **admin** user(s).  Otherwise, there will be no user with the permission needed to manage the roles in that table.  I can explain how to configure that if you really **do** want to use application managed roles.

**Note**: the "Access" tab in the UI should only appear if you have enabled application managed roles.  If you are seeing that tab without enabling application managed roles, then that's a bug.

## Questions:

1. Do you want to use application managed roles?
2. Are you seeing the "Access" tab?
3. Have you enabled application managed roles?

**Comment by EricWittmann** [comment]
I've done some preliminary testing of this and it does looks like the "Access" tab is appearing when it should not.  I'll dig into that more and fix the UI side of things.

Question (1) is still relevant probably.  Learning what you want. :)

**Comment by abhipatil2001** [comment]
Hi @EricWittmann 

Thanks for the explanation. After reviewing, here are my clarifications:

#### 1. Role Management Preference:

- I wish to use application-managed roles.
- I understand that using Apicurio’s database for role management may require additional configuration.
- Please let me know how I can proceed with enabling and managing application-managed roles.

#### 2. Access Tab Visibility:

- Despite using token-based roles, I can see the Access tab in the UI.
- Since this tab is meant for application-managed roles, its visibility in this case might be a **bug**.

#### 3. Application Managed Roles:

- I can confirm that application-managed roles are not enabled.
- I haven't set the`apicurio.auth.role-source` environment variable to `application`. I also tried explicitly setting it to `token`, but it didn't make any difference since the default value is already `token`. So, I preferred not to include this variable in the compose file.
- The registry logs also indicate that application-managed RBAC is not active.

**Note:** I have provided both docker compose variables and application logs in the issue.

Please let me know if there’s any further details or assistance you need.

**Comment by abhipatil2001** [comment]
Thanks for the update! That sounds great. I'll wait for your docker-compose file and give the snapshot build a try once it's ready. Looking forward to 3.0.7! :)

**Comment by EricWittmann** [comment]
OK here is the docker compose:

https://github.com/Apicurio/apicurio-registry/blob/main/distro/docker-compose/in-memory-with-rbac-app/docker-compose.yml

So what's going on?  The key configs are:

https://github.com/Apicurio/apicurio-registry/blob/main/distro/docker-compose/in-memory-with-rbac-app/docker-compose.yml#L31-L35

```yaml
      apicurio.auth.role-based-authorization: "true"
      apicurio.auth.role-source: "application"
      apicurio.auth.admin-override.enabled: "true"
      apicurio.auth.admin-override.type: "user"
      apicurio.auth.admin-override.user: "admin"
```

Those properties do the following:

1. Enable RBAC
2. Set the role source to "application" (as discussed above)
3. Enable the "admin override" feature
4. Set the admin override type to "user"
5. Configure the admin user name to be `admin`

I think (1) and (2) are obvious.  But (3), (4), and (5) may not be.

These are needed because there is a chicken/egg problem with application managed roles.  If the roles are in the database, and only Admin users are allowed to grant roles, then how can **any** user ever initially get access?  That is what "admin override" is used for.  You can think of it as an "extra" way to grant admin privs to a user.

In this case I'm using the principal name as the way to identify an Admin user.  If a user with principal `admin` logs in successfully, then they will be an admin.  That becomes the super-user I guess.  That user can then grant additional roles to other users via the UI or REST API.

There are other ways to configure the admin override, such as looking into the token for an assigned role.  It's up to you.
