### ISSUE TITLE
Apicurio Schema Registry UI - not coming up, referring to default_client instead of the apicurio_ui

### ISSUE THREAD

**Issue by karanalang** [Apicurio/apicurio-registry#6213]
I've deployed Apicurio Schema Registry 3.0.7 using yamls (not Operator). Keycloak is installedf (version - 26.1.5).

The pods have come up, but UI is not coming up .. error in the keycloak logs -

```
Id="default_client", userId="null", ipAddress="10.220.5.44", error="client_not_found"
2025-05-06 19:15:23,495 WARN  [org.keycloak.events] (executor-thread-272) type="LOGIN_ERROR", realmId="e8920d85-eb9f-42a2-885a-728d29fcaf96", realmName="readonly-realm", clientId="default_client", userId="null", ipAddress="10.220.5.44", error="client_not_found"
2025-05-06 19:15:32,159 WARN  [org.keycloak.events] (executor-thread-276) type="LOGIN_ERROR", realmId="e8920d85-eb9f-42a2-885a-728d29fcaf96", realmName="readonly-realm", clientId="default_client", userId="null", ipAddress="10.220.5.44", error="client_not_found"
2025-05-06 19:18:21,289 WARN  [org.keycloak.events] (executor-thread-278) type="LOGIN_ERROR", realmId="e8920d85-eb9f-42a2-885a-728d29fcaf96", realmName="readonly-realm", clientId="default_client", userId="null", ipAddress="10.220.5.44", error="client_not_found"

``` 

Somehow, it is trying to use "default_client" instead of client - "apicurio_ui" that I have created in realm -> 'readonly-realm'

On the UI, it is getting redirected to -

```
https://keycloak.vkp.versa-vani.com/realms/readonly-realm/protocol/openid-connect/auth?client_id=default_client&redirect_uri=http%3A%2F%2Flocalhost%3A8080&response_type=code&scope=openid+profile+email&state=0b25f432af4a4eee887d8f2078c7dad5&code_challenge=v0bBCKbpO6fcylykofrySorcV-FjJ65oqKPHElDD-zU&code_challenge_method=S256 400 (Bad Request)
```

On Keycloak, here is the setup - 

realm - readonly-realm
clients created -
1. apicurio-ui  

- This is public client  i.e. Client Authentication set to Off
- Standard Flow & Direct Access grants - checked 

Valid redirect URIs - https://apicurio-ui.vkp.versa-vani.com/*
Web Origins - '+'

Private Clients used by the Schema Registry
3. apicurio-registry
(Service account roles assigned  - sr-admin, sr-developer, sr-readonly) 
5. apicurio-readonly
(Service account role assigned - sr-readonly) 
7. apicurio-developer  
(Service account role assigned - sr-developer) 

here is yaml for the UI:

```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: apicurio-registry-ui
  labels:
    app: apicurio-registry-ui
spec:
  replicas: 2
  selector:
    matchLabels:
      app: apicurio-registry-ui
  template:
    metadata:
      labels:
        app: apicurio-registry-ui
    spec:
      containers:
        - name: apicurio-registry-ui
          image: apicurio/apicurio-registry-ui:3.0.7
          env:
            - name: REGISTRY_API_URL
              value: "https://apicurio-sr.vkp.versa-vani.com/apis/registry/v3"
            - name: REGISTRY_UI_CONFIG_APIURL
              value: "https://apicurio-sr.vkp.versa-vani.com/apis/registry/v3"
            - name: REGISTRY_UI_CONFIG_UIURL
              value: "https://apicurio-ui.vkp.versa-vani.com/" # removed /ui
            - name: REGISTRY_UI_CONFIG_AUTH_CLIENT_ID
              value: "apicurio-ui"
            - name: REGISTRY_UI_CONFIG_CORS_ALLOWED_ORIGINS
              value: "*"   
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
---

apiVersion: v1
kind: Service
metadata:
  name: apicurio-registry-ui
  labels:
    app: apicurio-registry-ui
spec:
  selector:
    app: apicurio-registry-ui
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP
```

yaml for the Schema Registry -

```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: apicurio-registry
  labels:
    app: apicurio-registry
spec:
  replicas: 3
  selector:
    matchLabels:
      app: apicurio-registry
  template:
    metadata:
      labels:
        app: apicurio-registry
    spec:
      containers:
        - name: apicurio-registry
          image: apicurio/apicurio-registry:3.0.7
          env:
            # Database configuration (adjust as needed)
            - name: APICURIO_STORAGE_KIND
              value: sql
            - name: APICURIO_STORAGE_SQL_KIND
              value: postgresql
            - name: APICURIO_DATASOURCE_URL
              value: jdbc:postgresql://my-postgres-postgresql.apicurio307.svc.cluster.local:5432/postgres
            - name: APICURIO_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: apicurio-db-secret
                  key: POSTGRES_USER
            - name: APICURIO_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: apicurio-db-secret
                  key: POSTGRES_PASSWORD

            # OIDC Authentication with Keycloak
            - name: QUARKUS_OIDC_TENANT_ENABLED
              value: "true"
            - name: QUARKUS_OIDC_AUTH_SERVER_URL
              value: "https://keycloak.vkp.versa-vani.com/realms/readonly-realm"
            - name: QUARKUS_OIDC_CLIENT_ID
              value: "apicurio-registry"
            - name: QUARKUS_OIDC_CREDENTIALS_SECRET
              value: "pwd"

            # Role-based authorization
            - name: APICURIO_AUTH_ROLE_BASED_AUTHORIZATION
              value: "true"
            - name: APICURIO_AUTH_ROLES_ADMIN
              value: "sr-admin"
            - name: APICURIO_AUTH_ROLES_DEVELOPER
              value: "sr-developer"
            - name: APICURIO_AUTH_ROLES_READONLY
              value: "sr-readonly"
            - name: APICURIO_AUTH_ROLE_SOURCE
              value: "token"

            # Logging (optional, for debugging)
            - name: QUARKUS_LOG_LEVEL
              value: "DEBUG"
            - name: QUARKUS_LOG_CATEGORY__IO_APICURIO_REGISTRY_AUTH__LEVEL
              value: "DEBUG"
            - name: QUARKUS_LOG_CATEGORY__IO_APICURIO_REGISTRY__LEVEL
              value: "DEBUG"
            - name: QUARKUS_LOG_CATEGORY__IO_QUARKUS_OIDC__LEVEL
              value: "DEBUG"

            # for CORS ERROR
            - name: QUARKUS_HTTP_CORS_ORIGINS
              value: "https://apicurio-ui.vkp.versa-vani.com"
            - name: QUARKUS_HTTP_CORS_ENABLED
              value: "true"
            - name: QUARKUS_HTTP_CORS_HEADERS
              value: "accept, authorization, content-type, x-requested-with"
            - name: QUARKUS_HTTP_CORS_METHODS
              value: "GET, PUT, POST, DELETE, OPTIONS"


          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: "250m"
              memory: "512Mi"
            limits:
              cpu: "1"
              memory: "2Gi"
          livenessProbe:
            httpGet:
              path: /health/live
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /health/ready
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 10

```

What need to be done to get the UI working ?

Attached are screenshots of the apicurio-ui client

![Image](https://github.com/user-attachments/assets/be11ce40-caf8-4a03-9f6e-405386688a35)
![Image](https://github.com/user-attachments/assets/fd99ff9b-a464-46e7-bfc9-efd1249ac83f)

**Comment by karanalang** [comment]
hello - any updates on this ?

**Comment by karanalang** [comment]
Hi @EricWittmann ,

Here is the current env in UI yaml (all other environment variables are removed from UI yaml)

```
env:
            - name: REGISTRY_AUTH_TYPE
              value: "oidc"
            - name: REGISTRY_API_URL
              value: "https://apicurio-sr.vkp.versa-vani.com/apis/registry/v3"
            - name: REGISTRY_AUTH_URL
              value: "https://keycloakv3.vkp.versa-vani.com/realms/apicurio"
```

On the Schema Registry, here are. the variables -

```
- env:
        - name: APICURIO_STORAGE_KIND
          value: sql
        - name: APICURIO_STORAGE_SQL_KIND
          value: postgresql
        - name: APICURIO_DATASOURCE_URL
          value: jdbc:postgresql://my-postgres-postgresql.apicurio307.svc.cluster.local:5432/postgres
        - name: APICURIO_DATASOURCE_USERNAME
          valueFrom:
            secretKeyRef:
              key: POSTGRES_USER
              name: apicurio-db-secret
        - name: APICURIO_DATASOURCE_PASSWORD
          valueFrom:
            secretKeyRef:
              key: POSTGRES_PASSWORD
              name: apicurio-db-secret
        - name: QUARKUS_OIDC_TENANT_ENABLED
          value: "true"
        - name: QUARKUS_OIDC_AUTH_SERVER_URL
          value: https://keycloakv3.vkp.versa-vani.com/realms/apicurio
        - name: QUARKUS_OIDC_CLIENT_ID
          value: registry-api
        - name: APICURIO_UI_AUTH_OIDC_CLIENT_ID
          value: apicurio-registry
        - name: QUARKUS_HTTP_CORS_ORIGINS
          value: '*'
        - name: APICURIO_AUTH_ROLE_BASED_AUTHORIZATION
          value: "true"
        - name: APICURIO_AUTH_ROLES_ADMIN
          value: sr-admin
        - name: APICURIO_AUTH_ROLES_DEVELOPER
          value: sr-developer
        - name: APICURIO_AUTH_ROLES_READONLY
          value: sr-readonly
        - name: APICURIO_AUTH_ROLE_SOURCE
          value: token
        - name: QUARKUS_LOG_LEVEL
          value: DEBUG
        - name: QUARKUS_LOG_CATEGORY__IO_APICURIO_REGISTRY_AUTH__LEVEL
          value: DEBUG
        - name: QUARKUS_LOG_CATEGORY__IO_APICURIO_REGISTRY__LEVEL
          value: DEBUG
        - name: QUARKUS_LOG_CATEGORY__IO_QUARKUS_OIDC__LEVEL
          value: DEBUG
        - name: QUARKUS_HTTP_CORS_ENABLED
          value: "true"
        - name: QUARKUS_HTTP_CORS_HEADERS
          value: accept, authorization, content-type, x-requested-with
        - name: QUARKUS_HTTP_CORS_METHODS
          value: GET, PUT, POST, DELETE, OPTIONS
        - name: QUARKUS_HTTP_CORS_EXPOSED_HEADERS
          value: Location,Content-Disposition
        - name: QUARKUS_HTTP_CORS_ACCESS_CONTROL_ALLOW_CREDENTIALS
          value: "true"
        - name: QUARKUS_OIDC_PUBLIC_CLIENT
          value: "true"
        - name: APICURIO_AUTH_ALLOW_ANONYMOUS_READS
          value: "true"

```

here is the behavior ->

On the browser, when i go to the Registry UI -> https://apicurio-ui3.vkp.versa-vani.com/ .. it get redirected to keycloak URI and the error in keycloak is shown below 

logs in keycloak  -

```
2025-05-13 23:47:23,719 WARN  [org.keycloak.events] (executor-thread-10) type=LOGIN_ERROR, realmId=6605d477-6b21-4e0d-be7f-833dc22d09e5, clientId=apicurio-registry, userId=null, ipAddress=127.0.0.1, error=invalid_redirect_uri, redirect_uri=http://localhost:8080
```

The good news is .. the client Id is being recognized, but still showing error

Client -> apicurio-registry has the following configuration -

---

Client Authentication - OFF
StandardFlow - ON
Valid redirect URIs - https://apicurio-ui3.vkp.versa-vani.com/*
WebOrigins - https://apicurio-ui3.vkp.versa-vani.com/*, +


Pls let me know how to debug/fix this 

thanks!
