### ISSUE TITLE
Keycloak Integration with Apicurio-registry

### ISSUE THREAD

**Issue by Storkycold** [Apicurio/apicurio-registry#6232]
## Setting 

I have configured the Keycloak service to be accessible via HTTPS with a domain name. However, the actual Keycloak service itself runs over HTTP—I used a reverse proxy to expose it as HTTPS externally while the internal service communicates via HTTP.

After confirming that the Keycloak web page successfully loads over HTTPS, I proceeded to integrate Keycloak with Apicurio Registry.

<details>
<summary>Keycloak via HTTPS</summary>

<img width="500" alt="Image" src="https://github.com/user-attachments/assets/3b9a5505-9be3-474e-9dfa-2dec5cd9b6c8" />
</details>

## Problem 

Below is the YAML configuration I used for Apicurio Registry, including the Keycloak integration settings. In this setup, I expected that accessing the Apicurio Registry would automatically redirect me to the Keycloak login page. However, the expected redirect to Keycloak does not occur. Instead, an error related to HTTP/HTTPS mismatch appears.

So my question is:

- If Keycloak is exposed via HTTPS, does Apicurio Registry also need to be served over HTTPS for the integration to work properly?
- Also, is there a specific reason or technical rationale behind this behavior?

<img width="1678" alt="Image" src="https://github.com/user-attachments/assets/396ee6e1-d817-4456-b7bf-b5f3098416e3" />

<details>
<summary>Apicurio-registry settings</summary>

```
apiVersion: v1
kind: Service
metadata:
  name: apicurio-registry-service
  labels:
    app: apicurio-registry
spec:
  type: NodePort
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: 8080
    nodePort: 30349
  selector:
    app: apicurio-registry
---
apiVersion: registry.apicur.io/v1
kind: ApicurioRegistry
metadata:
  name: apicurio-registry
spec:
  configuration:
    persistence: "sql"
    sql:
      dataSource:
        url: "jdbc:postgresql://192.168.80.23:30021/apicurio" 
        userName: "postgres"
        password: "1234" 
    security: 
      keycloak: 
        url: "https://keycloak.medicalai.ai.kr"
        realm: "registry"
        apiClientId: "registry-api"
        uiClientId: "apicurio-registry"
```
</details>

endpoint works well. 

<details>
<summary>click to expand</summary>

```
kubectl exec -it apicurio-registry-deployment-7f4dffbb6d-ps24f -n apicurio -- curl -v https://keycloak.medicalai.ai.kr/realms/registry/.well-known/openid-configuration
*   Trying 192.168.1.101...
* TCP_NODELAY set
* Connected to keycloak.medicalai.ai.kr (192.168.1.101) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*   CAfile: /etc/pki/tls/certs/ca-bundle.crt
  CApath: none
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
* TLSv1.3 (IN), TLS handshake, Server hello (2):
* TLSv1.3 (IN), TLS handshake, [no content] (0):
* TLSv1.3 (IN), TLS handshake, Encrypted Extensions (8):
* TLSv1.3 (IN), TLS handshake, [no content] (0):
* TLSv1.3 (IN), TLS handshake, Certificate (11):
* TLSv1.3 (IN), TLS handshake, [no content] (0):
* TLSv1.3 (IN), TLS handshake, CERT verify (15):
* TLSv1.3 (IN), TLS handshake, [no content] (0):
* TLSv1.3 (IN), TLS handshake, Finished (20):
* TLSv1.3 (OUT), TLS change cipher, Change cipher spec (1):
* TLSv1.3 (OUT), TLS handshake, [no content] (0):
* TLSv1.3 (OUT), TLS handshake, Finished (20):
* SSL connection using TLSv1.3 / TLS_AES_256_GCM_SHA384
* ALPN, server accepted to use h2
* Server certificate:
*  subject: CN=keycloak.medicalai.ai.kr
*  start date: May  9 04:05:13 2025 GMT
*  expire date: Aug  7 04:05:12 2025 GMT
*  subjectAltName: host "keycloak.medicalai.ai.kr" matched cert's "keycloak.medicalai.ai.kr"
*  issuer: C=US; O=Let's Encrypt; CN=R10
*  SSL certificate verify ok.
* Using HTTP2, server supports multi-use
* Connection state changed (HTTP/2 confirmed)
* Copying HTTP/2 data in stream buffer to connection buffer after upgrade: len=0
* TLSv1.3 (OUT), TLS app data, [no content] (0):
* TLSv1.3 (OUT), TLS app data, [no content] (0):
* TLSv1.3 (OUT), TLS app data, [no content] (0):
* Using Stream ID: 1 (easy handle 0x5586a850e6f0)
* TLSv1.3 (OUT), TLS app data, [no content] (0):
> GET /realms/registry/.well-known/openid-configuration HTTP/2
> Host: keycloak.medicalai.ai.kr
> User-Agent: curl/7.61.1
> Accept: */*
>
* TLSv1.3 (IN), TLS handshake, [no content] (0):
* TLSv1.3 (IN), TLS handshake, Newsession Ticket (4):
* TLSv1.3 (IN), TLS handshake, [no content] (0):
* TLSv1.3 (IN), TLS handshake, Newsession Ticket (4):
* TLSv1.3 (IN), TLS app data, [no content] (0):
* Connection state changed (MAX_CONCURRENT_STREAMS == 128)!
* TLSv1.3 (OUT), TLS app data, [no content] (0):
* TLSv1.3 (IN), TLS app data, [no content] (0):
< HTTP/2 200
< date: Tue, 13 May 2025 06:27:41 GMT
< content-type: application/json;charset=UTF-8
< content-length: 6552
< cache-control: no-cache, must-revalidate, no-transform, no-store
< referrer-policy: no-referrer
< strict-transport-security: max-age=15724800; includeSubDomains
< x-content-type-options: nosniff
< x-frame-options: SAMEORIGIN
< x-xss-protection: 1; mode=block
<
{"issuer":"https://keycloak.medicalai.ai.kr/realms/registry","authorization_endpoint":"https://keycloak.medicalai.ai.kr/realms/registry/protocol/openid-connect/auth"*** 
```
</details>
