### ISSUE TITLE
Apicurio-registry RBAC integration with Keycloak

### ISSUE THREAD

**Issue by Storkycold** [Apicurio/apicurio-registry#6243]
Regarding https://github.com/Apicurio/apicurio-registry/issues/6232, I have resolved it through apicurio-registry with HTTPS. 

**In this issue, my genuine purpose is to use Apicurio API in UI with sr-admin, sr-developer.** 

## Problem 

Even though I set all the relevant environment variables (`e.g. ROLE_BASED_AUTHZ_ENABLED, REGISTRY_AUTH_ROLES_ADMIN, ROLE_BASED_AUTHZ_SOURCE`), problems described below persist. I logged in with my **sr-admin role account** and tried to change global rules. 

- `Access permissions needed`

<img width="1790" alt="Image" src="https://github.com/user-attachments/assets/4a69dfea-2b3d-4f36-873b-02f8ff31042d" />

- `{"status":401,"error":{"detail":"UnauthorizedException: User is not authenticated.","error_code":401,"message":"User is not authenticated.","name":"UnauthorizedException"},"jaxrsResponse":null}`

<img width="1525" alt="Image" src="https://github.com/user-attachments/assets/05d86bd7-a499-47c2-aef8-b2143a6258b7" />

According to the [Apicurio Registry documentation](https://www.apicur.io/registry/docs/apicurio-registry/2.4.x/getting-started/assembly-configuring-the-registry.html), I assumed that setting the `ROLE_BASED_AUTHZ_ENABLED: "true"` env variable, along with assigning the roles `sr-admin, sr-developer, and sr-readonly` would be sufficient. I also created the corresponding realm roles and assigned them to the user account in Keycloak.

e.g. 

- user name: admin-test
- role mapping: 
  - **apiClientID - registry-api: sr-admin(realm role)**, 
  - **uiClientID - apicurio-registry: sr-admin(realm role)**,
  - **realm role - sr-admin** 
    - I do admit that they may be redundant

<img width="1798" alt="Image" src="https://github.com/user-attachments/assets/3348e837-18c5-4020-973f-390bdbd8b9b3" />

## Question 

So my question is:

- Is there a specific reason or technical rationale behind this behavior?
 
- Do I need to configure a client secret for `apiClientId: registry-api` in order to use the Apicurio API?

- Are there any additional environment variables I need to set beyond those listed below?

<img src='https://github.com/user-attachments/assets/563cce6b-8d6a-4c28-8249-b996581fa1c1' width='49%' height='49%'>

## Setting 

- version: 2.6.x 
- image: quay.io/apicurio/apicurio-registry-sql:2.6.x-snapshot
- operator + deployment 
- reference: https://www.apicur.io/registry/docs/apicurio-registry-operator/1.2.0-dev-v2.6.x/assembly-operator-quickstart.html 

```bash 
kubectl get pod -n apicurio
NAME                                            READY   STATUS    RESTARTS   AGE
apicurio-registry-deployment-5784b4d889-vfnp6   1/1     Running   0          54m
apicurio-registry-operator-7ccc998449-8khff     1/1     Running   0          54m
```

## Configuration 

apicurio-registry works via nginx-proxy. 

**A cluster -> nginx-proxy -> B cluster** 

- A cluster: has TLS certificate, add ingress resource to route by host name. 
- nginx-proxy: internally activate apicurio-registry with HTTP. It's via HTTPS from A cluster to nginx-proxy. 
- B-cluster: where actual deployment, service of apicurio-registry exists. 

<details>
<summary>apicurio service, deployment</summary>

```
apiVersion: v1
kind: Service
metadata:
  name: apicurio-registry-service
  labels:
    app: apicurio-registry
spec:
  type: NodePort
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: 8080
    nodePort: 30349
  selector:
    app: apicurio-registry
---
apiVersion: registry.apicur.io/v1
kind: ApicurioRegistry
metadata:
  name: apicurio-registry
spec:
  configuration:
    persistence: "sql"
    sql:
      dataSource:
        url: "jdbc:postgresql://***/apicurio" 
        userName: "postgres"
        password: "1234" 
    security:
      keycloak:
        realm: "registry"
        url: "https://keycloak.domain.***"  
        apiClientId: "registry-api"
        uiClientId: "apicurio-registry"
    env: 
       - name: ROLE_BASED_AUTHZ_ENABLED
         value: "true"
       - name: REGISTRY_AUTH_OIDC_ENABLED 
         value: "true"
       - name: REGISTRY_AUTH_ROLES_ADMIN 
         value: "sr-admin"
       - name: REGISTRY_AUTH_ROLES_DEVELOPER 
         value: "sr-developer"
       - name: REGISTRY_AUTH_ROLES_READONLY
         value: "sr-readonly"
       - name: ROLE_BASED_AUTHZ_SOURCE
         value: "token"
```
</details>

I look forward to your response. 

Thanks.
