### ISSUE TITLE
Microsoft Entra login - 401

### ISSUE THREAD

**Issue by krystofrezac** [Apicurio/apicurio-registry#6329]
## Description

Login with Microsoft Entra doesn't work.
1. The redirect URI is now set to `<base-url>/explore`, even though our configuration (`APICURIO_UI_AUTH_OIDC_REDIRECT-URI`) doesn't contain `/explore`
2. After attempting to log in, a 401 error is returned. The UI displays the following error:

<img width="718" alt="Image" src="https://github.com/user-attachments/assets/2954c39b-4424-4874-9a92-0327e21bf80a" />

```json
{
   "responseHeaders": {
      "cache-control": [
         "no-cache",
         " no-store",
         " must-revalidate"
      ],
      "content-length": [
         "0"
      ],
      "date": [
         "Thu",
         " 12 Jun 2025 05:37:01 GMT"
      ],
      "expires": [
         "Wed",
         " 11 Jun 2025 05:37:01 GMT"
      ],
      "pragma": [
         "no-cache"
      ],
      "strict-transport-security": [
         "max-age=31536000; includeSubDomains"
      ],
      "www-authenticate": [
         "Bearer"
      ]
   },
   "responseStatusCode": 401
}
```

The login flow works correctly in version `3.0.7` with the same configuration.

**Registry
Version**: 3.0.9
**Persistence type**: postgresql

### Environment

Configuration:
```
# registry
    QUARKUS_OIDC_TENANT-ENABLED: 'true'
    QUARKUS_HTTP_CORS_ORIGINS: "*"
    APICURIO_AUTH_ROLE-BASED-AUTHORIZATION: 'true'
    QUARKUS_OIDC_ROLES_ROLE-CLAIM-PATH: roles
    APICURIO_AUTH_ANONYMOUS-READ-ACCESS_ENABLED: 'true'
    APICURIO_STORAGE_KIND: sql
    APICURIO_STORAGE_SQL_KIND: postgresql

    QUARKUS_OIDC_CLIENT-ID: <client-id>
    QUARKUS_OIDC_AUTH-SERVER-URL: https://login.microsoftonline.com/<tenant-id>/v2.0
    APICURIO_UI_AUTH_OIDC_CLIENT-ID: <client-id>
    APICURIO_UI_AUTH_OIDC_REDIRECT-URI: https://<base-url>

# ui
REGISTRY_API_URL: https://<base-url>/apis/registry/v3
```

### Steps to Reproduce

1. Open the Registry UI.
2. Attempt to log in using a Microsoft account.
3. Wait for the redirect to Apicurio.

### Expected vs Actual Behaviour

Expected:
- Successful login with Microsoft Entra.
- Redirect URI should respect the configured value (should NOT add `/explore`).

Actual:
- Login fails with a 401 error and the redirect URI is not as configured.

### Logs

[apicurio-logs.txt](https://github.com/user-attachments/files/20702982/apicurio-logs.txt)

Thank you for looking into it.

**Comment by EricWittmann** [comment]
So if I understand correctly, here is what happens (correct me if I'm wrong):

1. Navigate to apicurio-registry
2. Get redirected to MS Entra
3. Provide username/password to login
4. Login successful, redirected back to apicurio-registry (but now it's with `/explore`)
5. UI shows error page due to 401 error

Can you use the browser's Network tab (in the devtools) to check that a JWT is being sent in the failing REST API call?  Perhaps unpack the JWT to see what it looks like.  And finally, can you attach the application logs?

I think the `/explore` bit is just a red herring.  We did make a change to improve the UI redirect, so that you can deep link into the application and it will work even if you have to login first.  But we also made one or two auth token changes which could be the problem instead.

**Comment by krystofrezac** [comment]
Yes, you understand it correctly. 


Regarding the redirect URI with `/explore`: I mentioned this specifically because it required configuration changes on the Microsoft Entra side. Microsoft Entra would refuse to complete the authentication flow without having this exact redirect URI added to the allowed redirect URIs list in the app registration.


I checked the network calls and all requests include the JWT token in `Authorization` header. However, when I decode the JWT using jwt.io, it warns me about invalid signature, which might be the problem... But I checked token from `3.0.7` and it gives me same warning, so it might be irrelevant.

<img width="682" alt="Image" src="https://github.com/user-attachments/assets/348b22b2-d7dc-4af7-8e2c-f54a90cbaf50" />

The decoded JWT:

```json
{
  "aud": "00000003-0000-0000-c000-000000000000",
  "iss": "https://sts.windows.net/a0cac25b-4fde-4611-bdd6-46dbec7aaf2f/",
  "iat": 1749797060,
  "nbf": 1749797060,
  "exp": 1749801165,
  "acct": 0,
  "acr": "1",
  "aio": "AUQAu/8ZAAAAg3Ft646vO9t3LyRW6kY1bL0wolmbqmSz8hcRvtrrI4zAVPI8TXqJfzkqActg7WhbbXLcBoX7pgwAZt5ZCQRDww==",
  "amr": [
    "pwd"
  ],
  "app_displayname": "ApicurioRegistryAPI",
  "appid": "<redacted>",
  "appidacr": "0",
  "family_name": "Řezáč",
  "given_name": "Kryštof",
  "idtyp": "user",
  "ipaddr": "78.80.140.207",
  "name": "Kryštof Řezáč",
  "oid": "<redacted>",
  "platf": "5",
  "puid": "10032003985ED8F6",
  "rh": "1.Aa4AW8LKoN5PEUa91kbb7HqvLwMAAAAAAAAAwAAAAAAAAACuAOeuAA.",
  "scp": "User.Read profile openid email",
  "sid": "005d9139-ca73-083b-b5a9-08400353610c",
  "sub": "p66e-LClQFizaaXFThgmwHV-t-pfzWH8A1QGXnRTrOQ",
  "tenant_region_scope": "EU",
  "tid": "a0cac25b-4fde-4611-bdd6-46dbec7aaf2f",
  "unique_name": "<redacted>",
  "upn": "<redacted>",
  "uti": "7MaC4SrIU0C7PFNtrf0UAA",
  "ver": "1.0",
  "wids": [
    "cf1c38e5-3621-4004-a7cb-879624dced7c",
    "b79fbf4d-3ef9-4689-8143-76b194e85509"
  ],
  "xms_ftd": "XC7NTGk4Fx-RVnNZawmEDxfJxmUlxP9khWX8NP3HCSwBc3dlZGVuYy1kc21z",
  "xms_idrel": "12 1",
  "xms_st": {
    "sub": "en_6Ccd3AZoDmIX7Rteq-mB2rjhuHnN4JdHwjvCElv4"
  },
  "xms_tcdt": 1695285620,
  "xms_tdbr": "EU"
}
```

Decoded JWT from 3.0.7:
```json
{
  "aud": "00000003-0000-0000-c000-000000000000",
  "iss": "https://sts.windows.net/a0cac25b-4fde-4611-bdd6-46dbec7aaf2f/",
  "iat": 1749798365,
  "nbf": 1749798365,
  "exp": 1749802650,
  "acct": 0,
  "acr": "1",
  "aio": "AUQAu/8ZAAAAkE89GKeHI1Xv1Gk+1mXLWcUmWHnepTJMWA3towobxKgib0D1k7sf3Alk05v8OR4tdxOtU/xWrv6DIBak6hGMiQ==",
  "amr": [
    "pwd"
  ],
  "app_displayname": "ApicurioRegistryAPI",
  "appid": "<redacted>",
  "appidacr": "0",
  "family_name": "Řezáč",
  "given_name": "Kryštof",
  "idtyp": "user",
  "ipaddr": "78.80.140.207",
  "name": "Kryštof Řezáč",
  "oid": "c2c0e5eb-5c23-4dfd-bc03-0f69b1f348fa",
  "platf": "5",
  "puid": "10032003985ED8F6",
  "rh": "1.Aa4AW8LKoN5PEUa91kbb7HqvLwMAAAAAAAAAwAAAAAAAAACuAOeuAA.",
  "scp": "User.Read profile openid email",
  "sid": "005d9139-b134-6ed5-49dd-4b6395c65cd3",
  "sub": "p66e-LClQFizaaXFThgmwHV-t-pfzWH8A1QGXnRTrOQ",
  "tenant_region_scope": "EU",
  "tid": "a0cac25b-4fde-4611-bdd6-46dbec7aaf2f",
  "unique_name": "<redacted>",
  "upn": "<redacted>",
  "uti": "kGlVexMTeU2oPFgCyTcTAA",
  "ver": "1.0",
  "wids": [
    "cf1c38e5-3621-4004-a7cb-879624dced7c",
    "b79fbf4d-3ef9-4689-8143-76b194e85509"
  ],
  "xms_ftd": "8fn_7aS-p4drhQlCeZOkwFozsl26s0-aM6OAK5e1ZRwBc3dlZGVuYy1kc21z",
  "xms_idrel": "1 30",
  "xms_st": {
    "sub": "en_6Ccd3AZoDmIX7Rteq-mB2rjhuHnN4JdHwjvCElv4"
  },
  "xms_tcdt": 1695285620,
  "xms_tdbr": "EU"
}
``` 

I've already included the application logs. Please let me know if you need any specific sections from the logs or if additional logging information would be helpful.

**Comment by EricWittmann** [comment]
So the error is clearly `JWT rejected due to invalid signature` but now we have to figure out why.  Can you share your auth configuration settings?

**Comment by EricWittmann** [comment]
Note:  if everything works properly for you in 3.0.7, a change we made that may have caused this problem is this:

https://github.com/Apicurio/apicurio-common-ui-components/commit/5e378476ab1eb5697575589c7cc9cd4e0ea1248e

**Comment by krystofrezac** [comment]
Yeah, sure. You mean configuration of Entra application right?

We only touched the `Authentication` page and `App roles`

<img width="1320" alt="Image" src="https://github.com/user-attachments/assets/1fddaa5e-ad6f-401d-b260-53fb2d527150" />
<img width="952" alt="Image" src="https://github.com/user-attachments/assets/0a8b25ee-f00b-4148-8b8d-43bcee8326ac" />

```json
{
	"id": "045a9eac-98e4-461f-9ec9-cb0b62959498",
	"deletedDateTime": null,
	"appId": "<redacted>",
	"applicationTemplateId": null,
	"disabledByMicrosoftStatus": null,
	"createdDateTime": "2024-05-09T13:36:58Z",
	"displayName": "ApicurioRegistryAPI",
	"description": null,
	"groupMembershipClaims": null,
	"identifierUris": [
		"api://<redacted>"
	],
	"isDeviceOnlyAuthSupported": null,
	"isFallbackPublicClient": null,
	"nativeAuthenticationApisEnabled": null,
	"notes": null,
	"publisherDomain": "<redacted>",
	"serviceManagementReference": null,
	"signInAudience": "AzureADMyOrg",
	"tags": [],
	"tokenEncryptionKeyId": null,
	"samlMetadataUrl": null,
	"defaultRedirectUri": null,
	"certification": null,
	"optionalClaims": null,
	"requestSignatureVerification": null,
	"addIns": [],
	"api": {
		"acceptMappedClaims": null,
		"knownClientApplications": [],
		"requestedAccessTokenVersion": 2,
		"oauth2PermissionScopes": [],
		"preAuthorizedApplications": []
	},
	"appRoles": [
		{
			"allowedMemberTypes": [
				"User",
				"Application"
			],
			"description": "sr-developer apicurio role",
			"displayName": "sr-developer",
			"id": "b55ff40a-33a9-4576-83a2-cc91ab31cafa",
			"isEnabled": true,
			"origin": "Application",
			"value": "sr-developer"
		},
		{
			"allowedMemberTypes": [
				"User",
				"Application"
			],
			"description": "sr-admin apicurio role",
			"displayName": "sr-admin",
			"id": "7a83fd4d-dfae-4ff6-9550-1779b78eb694",
			"isEnabled": true,
			"origin": "Application",
			"value": "sr-admin"
		},
		{
			"allowedMemberTypes": [
				"User",
				"Application"
			],
			"description": "sr-readonly apicurio role",
			"displayName": "sr-readonly",
			"id": "e87e57aa-6ab9-4b2f-ae6e-92035629e62c",
			"isEnabled": true,
			"origin": "Application",
			"value": "sr-readonly"
		}
	],
	"info": {
		"logoUrl": null,
		"marketingUrl": null,
		"privacyStatementUrl": null,
		"supportUrl": null,
		"termsOfServiceUrl": null
	},
	"keyCredentials": [],
	"parentalControlSettings": {
		"countriesBlockedForMinors": [],
		"legalAgeGroupRule": "Allow"
	},
	"passwordCredentials": [],
	"publicClient": {
		"redirectUris": []
	},
	"requiredResourceAccess": [
		{
			"resourceAppId": "00000003-0000-0000-c000-000000000000",
			"resourceAccess": [
				{
					"id": "e1fe6dd8-ba31-4d61-89e7-88639da4683d",
					"type": "Scope"
				}
			]
		}
	],
	"verifiedPublisher": {
		"displayName": null,
		"verifiedPublisherId": null,
		"addedDateTime": null
	},
	"web": {
		"homePageUrl": null,
		"logoutUrl": null,
		"redirectUris": [],
		"implicitGrantSettings": {
			"enableAccessTokenIssuance": false,
			"enableIdTokenIssuance": true
		},
		"redirectUriSettings": []
	},
	"servicePrincipalLockConfiguration": {
		"isEnabled": true,
		"allProperties": true,
		"credentialsWithUsageVerify": true,
		"credentialsWithUsageSign": true,
		"identifierUris": false,
		"tokenEncryptionKeyId": true
	},
	"spa": {
		"redirectUris": [
			"http://localhost:3000/explore",
			"https:/<base-url>/explore",
			"https://<base-url>",
			"http://localhost:3000",
			"https://<base-url>/ui"
		]
	}
}
```

**Comment by krystofrezac** [comment]
`kid` matches one of the entries in jwks endpoint.

And the configuration of `QUARKUS_OIDC_CLIENT-ID` and `APICURIO_UI_AUTH_OIDC_CLIENT-ID` is the same. And `QUARKUS_OIDC_AUTH-SERVER-URL` contains correct tenant id. There isn't any other variable right?

**Comment by krystofrezac** [comment]
I've managed to configure another Entra application this time under my personal account. So I can share all the information with you. I still get the same error and same warning in jwt.io.

<img width="480" alt="Image" src="https://github.com/user-attachments/assets/343693f9-f923-4cfb-9008-b4df40b34231" />

This is my testing docker-compose:
```yaml
services:
  apicurio-registry:
    image: apicurio/apicurio-registry:3.0.9
    ports:
      - '8080:8080'
    environment:
      # base
      QUARKUS_OIDC_TENANT-ENABLED: 'true'
      QUARKUS_HTTP_CORS_ORIGINS: "*"
      APICURIO_AUTH_ROLE-BASED-AUTHORIZATION: 'true'
      QUARKUS_OIDC_ROLES_ROLE-CLAIM-PATH: roles
      APICURIO_AUTH_ANONYMOUS-READ-ACCESS_ENABLED: 'true'
      APICURIO_STORAGE_KIND: sql
      APICURIO_STORAGE_SQL_KIND: postgresql

      APICURIO_DATASOURCE_URL: jdbc:postgresql://host.docker.internal:5432/apicurio
      APICURIO_DATASOURCE_USERNAME: postgres
      APICURIO_DATASOURCE_PASSWORD: postgres

      # dev
      QUARKUS_OIDC_CLIENT-ID: 7ab4dbf7-fa21-4631-ab48-6193d3f411a8
      QUARKUS_OIDC_AUTH-SERVER-URL: https://login.microsoftonline.com/32a7e3b3-08fb-4893-bdfe-466d22c8d00b/v2.0

      # UI
      APICURIO_UI_AUTH_OIDC_CLIENT-ID: 7ab4dbf7-fa21-4631-ab48-6193d3f411a8
      APICURIO_UI_AUTH_OIDC_REDIRECT-URI: http://localhost:3000

  apicurio-registry-ui:
    image: apicurio/apicurio-registry-ui:3.0.9
    ports:
      - '3000:8080'
    environment:
      REGISTRY_API_URL: http://localhost:8080/apis/registry/v3
```

**Comment by EricWittmann** [comment]
OK let me see if I can try that locally.

**Comment by EricWittmann** [comment]
Could you add `ewittman@redhat.com` as a user to that tenant?

**Comment by krystofrezac** [comment]
Sure. I've sent you an invitation.

**Comment by EricWittmann** [comment]
That's perfect, thanks @krystofrezac - I've reproduced the issue locally using your configuration.  I'll look into this first thing on Monday and report back.  Hopefully it's OK if you leave that Entra tenant up and running for a little bit.  I don't otherwise have access to Entra.

**Comment by EricWittmann** [comment]
OK I've spent a little bit of time reproducing this today.  I reverted the access token/id token change we made, but predictably that didn't change the outcome.  I'm still getting a signature invalid error with the JWT.  I confess I do not know how the IDP actually signs a JWT or how the application verifies the signature.  I'm curious now so will look into that for my own learning.

That said, I reverted the docker compose to use version `3.0.7` since you reported that version was working.  However, I still get the exact same error with 3.0.7 that I'm seeing with 3.0.9.

Can you confirm that you can get 3.0.7 working?  If you can, maybe there was some config difference?

**Comment by krystofrezac** [comment]
I had a mistake in my Entra configuration - I hadn’t assigned us the `sr-developer` role, so I was getting a 403. Once I fixed that, everything worked on `3.0.7` without any config changes. After downgrading, I did need to clear browser storage.

The JWT signature now also seems to be verified 🙂. This might be because I clicked this button:

<img width="1790" alt="Image" src="https://github.com/user-attachments/assets/a2171794-6f02-4f6e-b733-c95132481b17" />

**Comment by EricWittmann** [comment]
PR opened:  

* https://github.com/Apicurio/apicurio-registry/pull/6339

**Comment by EricWittmann** [comment]
Here is my working docker compose:

```
services:
  apicurio-registry-9:
    image: apicurio/apicurio-registry:3.0.9
    ports:
      - '8080:8080'
    environment:
      # base
      QUARKUS_OIDC_TENANT-ENABLED: 'true'
      QUARKUS_HTTP_CORS_ORIGINS: "*"
      APICURIO_AUTH_ROLE-BASED-AUTHORIZATION: 'true'
      QUARKUS_OIDC_ROLES_ROLE-CLAIM-PATH: roles
      APICURIO_AUTH_ANONYMOUS-READ-ACCESS_ENABLED: 'true'

      # dev
      QUARKUS_OIDC_CLIENT-ID: 7ab4dbf7-fa21-4631-ab48-6193d3f411a8
      QUARKUS_OIDC_AUTH-SERVER-URL: "https://login.microsoftonline.com/32a7e3b3-08fb-4893-bdfe-466d22c8d00b/v2.0"

      # UI
      APICURIO_UI_AUTH_OIDC_CLIENT-ID: 7ab4dbf7-fa21-4631-ab48-6193d3f411a8
      APICURIO_UI_AUTH_OIDC_REDIRECT-URI: "http://localhost:3000"

  apicurio-registry-ui:
    image: apicurio/apicurio-registry-ui:latest-snapshot
    ports:
      - '3000:8080'
    environment:
      REGISTRY_API_URL: "http://localhost:8080/apis/registry/v3"
      REGISTRY_AUTH_TYPE: oidc
      REGISTRY_AUTH_TOKEN_TYPE: id
      REGISTRY_AUTH_LOG_TOKENS: 'true'
```
